export const SUPPORTED_LANGUAGES = [
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    region: 'Andhra Pradesh & Telangana',
    script: 'Telugu',
    greeting: 'నమస్కారం!',
    speakers: '96M+ Speakers',
    badge: 'Popular South Indian',
    audioText: 'నమస్కారం! తెలుగు నేర్చుకుందాం.',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    region: 'Tamil Nadu & Puducherry',
    script: 'Tamil',
    greeting: 'வணக்கம்!',
    speakers: '85M+ Speakers',
    badge: 'Classical South Indian',
    audioText: 'வணக்கம்! தமிழ் படிப்போம்.',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    region: 'Karnataka',
    script: 'Kannada',
    greeting: 'ನಮಸ್ಕಾರ!',
    speakers: '45M+ Speakers',
    badge: 'Heritage South Indian',
    audioText: 'ನಮಸ್ಕಾರ! ಕನ್ನಡ ಕಲಿಯೋಣ.',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    region: 'Kerala & Lakshadweep',
    script: 'Malayalam',
    greeting: 'നമസ്കാരം!',
    speakers: '38M+ Speakers',
    badge: '100% Literacy State',
    audioText: 'നമസ്കാരം! മലയാളം പഠിക്കാം.',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    flag: '🇮🇳',
    region: 'Northern & Central India',
    script: 'Devanagari',
    greeting: 'नमस्ते!',
    speakers: '500M+ Speakers',
    badge: 'National Language',
    audioText: 'नमस्ते! हिंदी सीखें।',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    region: 'Global & Professional',
    script: 'Latin',
    greeting: 'Hello & Welcome!',
    speakers: 'Global Standard',
    badge: 'Career & Global',
    audioText: 'Hello and welcome to NeoRead!',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇧🇩',
    region: 'West Bengal & Bangladesh',
    script: 'Bengali',
    greeting: 'নমস্কার!',
    speakers: '300M+ Speakers',
    badge: 'Eastern India',
    audioText: 'নমস্কার!',
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    region: 'Maharashtra',
    script: 'Devanagari',
    greeting: 'नमस्कार!',
    speakers: '83M+ Speakers',
    badge: 'Western India',
    audioText: 'नमस्कार!',
  },
];

export const ONBOARDING_REASONS = [
  {
    id: 'career',
    icon: '💼',
    title: 'Career & Job Opportunities',
    description: 'Qualify for regional jobs, civil tests, and workplace communication',
    popular: true,
  },
  {
    id: 'daily_life',
    icon: '🧭',
    title: 'Travel, Signs & Daily Living',
    description: 'Read bus boards, shop signs, market price tags, and street directions',
    popular: true,
  },
  {
    id: 'brain_training',
    icon: '🧠',
    title: 'Brain Training & Mental Fitness',
    description: 'Exercise memory, cognitive speed, and active reading comprehension',
    popular: false,
  },
  {
    id: 'family_culture',
    icon: '👨‍👩‍👧‍👦',
    title: 'Connect with Family & Heritage',
    description: 'Read letters, chat with elders, and preserve cultural roots',
    popular: false,
  },
  {
    id: 'reading_books',
    icon: '📚',
    title: 'Read Books, News & Literature',
    description: 'Enjoy regional newspapers, bedtime stories, and classic literature',
    popular: false,
  },
  {
    id: 'school_exams',
    icon: '🏫',
    title: 'School, College & Kids Support',
    description: 'Assist children with homework and prepare for state board syllabus',
    popular: false,
  },
];

export const ONBOARDING_NEEDS = [
  {
    id: 'phonics',
    icon: '🔤',
    title: 'Alphabet & Letter Sounds',
    description: 'Learn script, consonants, vowels, and acoustic sound matching',
  },
  {
    id: 'vocabulary',
    icon: '👁️',
    title: 'Everyday Words & Sight Words',
    description: 'Essential common vocabulary for grocery, health, numbers, and family',
  },
  {
    id: 'reading',
    icon: '📖',
    title: 'Sentence & Story Reading',
    description: 'Read illustrated short stories, public notices, and daily paragraphs',
  },
  {
    id: 'writing',
    icon: '✍️',
    title: 'Spelling & Writing Practice',
    description: 'Master writing letter curves, accurate spelling, and form completion',
  },
  {
    id: 'functional',
    icon: '🏥',
    title: 'Real-World Practical Documents',
    description: 'Understand electricity bills, bank deposit forms, and hospital slips',
  },
];

export const ONBOARDING_DAILY_GOALS = [
  {
    id: 'casual',
    icon: '⚡',
    timeMinutes: 5,
    hoursDisplay: '5 mins / day',
    levelTitle: 'Casual Learner',
    description: 'Quick daily bite-sized lessons. Perfect for busy routines.',
    pace: 'Relaxed & Steady',
    xpMultiplier: '1x XP',
  },
  {
    id: 'regular',
    icon: '🚀',
    timeMinutes: 15,
    hoursDisplay: '15 mins / day',
    levelTitle: 'Regular Practice',
    description: 'Recommended pace for steady, confident reading growth.',
    pace: 'Recommended',
    recommended: true,
    xpMultiplier: '1.5x XP',
  },
  {
    id: 'serious',
    icon: '🔥',
    timeMinutes: 30,
    hoursDisplay: '30 mins / day',
    levelTitle: 'Serious Reader',
    description: 'Fast-track literacy. Complete full reading modules each week.',
    pace: 'Fast Progress',
    xpMultiplier: '2x XP',
  },
  {
    id: 'intense',
    icon: '🏆',
    timeMinutes: 60,
    hoursDisplay: '60+ mins / day (1+ hr)',
    levelTitle: 'Intensive Fluency',
    description: 'Deep immersion for rapid fluency, spelling, and story mastery.',
    pace: 'Maximum Speed',
    xpMultiplier: '3x XP',
  },
];

export const ONBOARDING_LEVELS = [
  {
    id: 'beginner',
    icon: '🌱',
    title: 'Start from the Very Beginning',
    subtitle: 'Brand new to this language script and alphabet',
    badge: 'Level 1 Phonics',
  },
  {
    id: 'elementary',
    icon: '🌿',
    title: 'I Know a Few Words & Letters',
    subtitle: 'Can recognize basic letters and common high-frequency words',
    badge: 'Level 2 Basics',
  },
  {
    id: 'spoken_only',
    icon: '🗣️',
    title: 'I Can Speak, But Cannot Read',
    subtitle: 'Fluent in speaking, but need help reading and writing script',
    badge: 'Level 2 Bridge',
  },
  {
    id: 'intermediate',
    icon: '⚡',
    title: 'Intermediate Reader Refreshing Skills',
    subtitle: 'Can read simple text, want to improve speed and vocabulary',
    badge: 'Level 3 Reader',
  },
];


export const PROFICIENCY_LEVELS = {
  unassessed: {
    key: 'unassessed',
    label: 'Unassessed',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-300',
    description: 'Initial assessment recommended to benchmark reading baseline.',
  },
  beginner: {
    key: 'beginner',
    label: 'Level 1: Novice Reader',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-300',
    description: 'Mastering alphabet, short vowels, and high-frequency 3-letter sight words.',
  },
  elementary: {
    key: 'elementary',
    label: 'Level 2: Elementary Reader',
    badgeClass: 'bg-blue-100 text-blue-800 border-blue-300',
    description: 'Reading basic compound words, short sentences, and everyday signs.',
  },
  intermediate: {
    key: 'intermediate',
    label: 'Level 3: Functional Reader',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    description: 'Understanding multi-paragraph stories, forms, bills, and structured sentences.',
  },
  advanced: {
    key: 'advanced',
    label: 'Level 4: Fluent Reader',
    badgeClass: 'bg-purple-100 text-purple-800 border-purple-300',
    description: 'Confident in functional, workplace, and expressive reading and writing.',
  },
};

export const CONTENT_TYPES = [
  { id: 'all', label: 'All Content Types' },
  { id: 'letter_phonics', label: '🔤 Alphabet & Phonics' },
  { id: 'sight_words', label: '👁️ Sight Words' },
  { id: 'sentence_builder', label: '🧩 Sentence Builder' },
  { id: 'short_story', label: '📖 Short Stories' },
  { id: 'functional_text', label: '🏥 Daily Life & Forms' },
];

export const TARGET_SKILLS_OPTIONS = [
  { id: 'phonics', label: 'Alphabet & Letter Sounds' },
  { id: 'vocabulary', label: 'Everyday Words & Vocabulary' },
  { id: 'reading', label: 'Sentence & Story Reading' },
  { id: 'writing', label: 'Spelling & Sentence Formation' },
  { id: 'comprehension', label: 'Understanding Context & Meaning' },
];
