/**
 * Client-Side Diagnostic Question Bank for Multilingual Initial Assessment
 * Supported Languages:
 *  1. Telugu (te)
 *  2. Tamil (ta)
 *  3. Kannada (kn)
 *  4. Malayalam (ml)
 *  5. Hindi (hi)
 *  6. English (en)
 *  7. Bengali (bn)
 *  8. Marathi (mr)
 * Age Cohorts:
 *  - kids (Age 3-11): Phonics, letter acoustic recognition, sight words
 *  - teens (Age 12-17): Vocabulary, sentence structure, story comprehension
 *  - adults (Age 18+): Functional literacy, public signs, medical notices, bank slips
 */

export const CLIENT_DIAGNOSTIC_QUESTIONS = {
  // 1. TELUGU
  te: {
    name: 'Telugu',
    nativeName: 'తెలుగు',
    kids: [
      {
        questionId: 'te_k_1',
        type: 'multiple_choice',
        prompt: 'క్రింది అక్షరాలలో "అ" (అమ్మ) అక్షరాన్ని గుర్తించండి:',
        options: ['అ', 'క', 'ర', 'మ'],
        correctAnswer: 'అ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"అ" మొదటి తెలుగు అచ్చు (అమ్మ).',
      },
      {
        questionId: 'te_k_2',
        type: 'multiple_choice',
        prompt: '"క - లం" కలిపితే ఏ పదం అవుతుంది?',
        options: ['కలం', 'కడవ', 'కమలం', 'కలవర'],
        correctAnswer: 'కలం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"క" మరియు "లం" కలిపితే "కలం" (Pen) అవుతుంది.',
      },
      {
        questionId: 'te_k_3',
        type: 'multiple_choice',
        prompt: 'మనకు పాలు ఇచ్చే జంతువు ఏది?',
        options: ['ఆవు', 'చేప', 'పిల్లి', 'కాకి'],
        correctAnswer: 'ఆవు',
        points: 20,
        skillCategory: 'reading',
        explanation: 'ఆవు మనకు పాలు ఇస్తుంది.',
      },
      {
        questionId: 'te_k_4',
        type: 'reading_passage',
        passage: 'రాజు బడికి వెళ్ళాడు. అక్కడ స్నేహితులతో ఆడుకున్నాడు. పుస్తకం చదివాడు.',
        prompt: 'రాజు ఎక్కడికి వెళ్ళాడు?',
        options: ['బడికి', 'తోటకు', 'సినిమాకి', 'ఊరికి'],
        correctAnswer: 'బడికి',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'వాక్యంలో "రాజు బడికి వెళ్ళాడు" అని ఉంది.',
      },
      {
        questionId: 'te_k_5',
        type: 'multiple_choice',
        prompt: '"ఆవు పాలు ఇస్తుంది" - ఈ వాక్యంలో మొదటి పదం ఏది?',
        options: ['ఆవు', 'పాలు', 'ఇస్తుంది', 'పుస్తకం'],
        correctAnswer: 'ఆవు',
        points: 20,
        skillCategory: 'writing',
        explanation: 'వాక్యంలోని మొదటి పదం "ఆవు".',
      },
    ],
    teens: [
      {
        questionId: 'te_t_1',
        type: 'multiple_choice',
        prompt: '"జ్ఞానం" అనే పదంలోని సరైన సంయుక్తాక్షరాన్ని గుర్తించండి:',
        options: ['జ్ఞ', 'శ్వ', 'త్ర', 'క్ష'],
        correctAnswer: 'జ్ఞ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"జ్ఞానం" లో "జ్ఞ" సంయుక్తాక్షరం ఉంది.',
      },
      {
        questionId: 'te_t_2',
        type: 'multiple_choice',
        prompt: '"విద్యార్థులు గ్రంథాలయంలో ________ చదువుతున్నారు."',
        options: ['పుస్తకాలు', 'నీళ్ళు', 'చెట్లు', 'రహదారులు'],
        correctAnswer: 'పుస్తకాలు',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'గ్రంథాలయంలో పుస్తకాలు చదువుతారు.',
      },
      {
        questionId: 'te_t_3',
        type: 'multiple_choice',
        prompt: 'సరైన వాక్య నిర్మాణాన్ని ఎంచుకోండి:',
        options: [
          'సూర్యుడు తూర్పున ఉదయిస్తాడు.',
          'ఉదయిస్తాడు తూర్పున సూర్యుడు.',
          'తూర్పున సూర్యుడు పడుకుంటాడు.',
          'సూర్యుడు పశ్చిమాన ఉదయిస్తాడు.',
        ],
        correctAnswer: 'సూర్యుడు తూర్పున ఉదయిస్తాడు.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'వ్యాకరణపరంగా సరైన వాక్యం: సూర్యుడు తూర్పున ఉదయిస్తాడు.',
      },
      {
        questionId: 'te_t_4',
        type: 'reading_passage',
        passage: 'చెట్లు మనకు స్వచ్ఛమైన ప్రాణవాయువును ఇస్తాయి. పర్యావరణ పరిరక్షణకు ప్రతి ఒక్కరూ మొక్కలు నాటాలి.',
        prompt: 'చెట్లు మనకు ఏమి ఇస్తాయి?',
        options: ['స్వచ్ఛమైన ప్రాణవాయువు', 'ప్లాస్టిక్ వ్యర్థాలు', 'శబ్ద కాలుష్యం', 'పొగ'],
        correctAnswer: 'స్వచ్ఛమైన ప్రాణవాయువు',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'చెట్లు మనకు స్వచ్ఛమైన ఆక్సిజన్ (ప్రాణవాయువు) అందిస్తాయి.',
      },
      {
        questionId: 'te_t_5',
        type: 'multiple_choice',
        prompt: '"విజయం" పదానికి వ్యతిరేక పదం ఏది?',
        options: ['అపజయం', 'సంతోషం', 'గెలుపు', 'ఉత్సాహం'],
        correctAnswer: 'అపజయం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'విజయం కి వ్యతిరేక పదం అపజయం.',
      },
    ],
    adults: [
      {
        questionId: 'te_a_1',
        type: 'multiple_choice',
        prompt: 'బస్సు బోర్డుపై "హైదరాబాద్" అని రాసి ఉన్న సరైన అక్షర రూపాన్ని గుర్తించండి:',
        options: ['హైదరాబాద్', 'హైదరాబాదు', 'హైదరబాద', 'హేదరాబాద్'],
        correctAnswer: 'హైదరాబాద్',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'సరైన స్పెల్లింగ్: హైదరాబాద్.',
      },
      {
        questionId: 'te_a_2',
        type: 'multiple_choice',
        prompt: 'ఆసుపత్రిలో అత్యవసర చికిత్స అందించే విభాగం ఏది?',
        options: ['అత్యవసర చికిత్సా విభాగం', 'సినిమా హాలు', 'బస్సు స్టాప్', 'రైల్వే టికెట్'],
        correctAnswer: 'అత్యవసర చికిత్సా విభాగం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ఆసుపత్రులలో వైద్య సేవలు అందించేది అత్యవసర చికిత్సా విభాగం (Emergency).',
      },
      {
        questionId: 'te_a_3',
        type: 'reading_passage',
        passage: 'విద్యుత్ బిల్లు చెల్లింపు చివరి తేదీ: 25 మార్చి 2026. ఆలస్య రుసుము రూ. 50 వర్తిస్తుంది.',
        prompt: 'బిల్లు గడువు తేదీ ఎప్పుడు?',
        options: ['25 మార్చి 2026', '1 జనవరి 2026', '10 ఏప్రిల్ 2026', '30 మే 2026'],
        correctAnswer: '25 మార్చి 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'నోటీసులో స్పష్టంగా చివరి తేదీ 25 మార్చి 2026 అని ఉంది.',
      },
      {
        questionId: 'te_a_4',
        type: 'multiple_choice',
        prompt: 'బ్యాంకులో డబ్బు జమ చేసే ఫారమ్‌లో మీ సంతకం ఎక్కడ చేయాలి?',
        options: ['డిపాజిటర్ సంతకం వద్ద', 'తేదీ వద్ద', 'బ్యాంకు సీల్ పైన', 'బ్యాంకు మేనేజర్ స్థానంలో'],
        correctAnswer: 'డిపాజిటర్ సంతకం వద్ద',
        points: 20,
        skillCategory: 'writing',
        explanation: 'డిపాజిటర్ సంతకం నిర్దేశించిన స్థానంలో చేయాలి.',
      },
      {
        questionId: 'te_a_5',
        type: 'multiple_choice',
        prompt: '"మందులు ఆహారం తర్వాత మాత్రమే వేసుకోవాలి" - దీని అర్థం ఏమిటి?',
        options: [
          'భోజనం చేసిన తర్వాత మందు వేసుకోవాలి',
          'ఖాళీ కడుపుతో మాత్రమే వేసుకోవాలి',
          'రాత్రి నిద్రపోయే ముందు మాత్రమే వేసుకోవాలి',
          'ఎప్పుడైనా వేసుకోవచ్చు',
        ],
        correctAnswer: 'భోజనం చేసిన తర్వాత మందు వేసుకోవాలి',
        points: 20,
        skillCategory: 'reading',
        explanation: '"ఆహారం తర్వాత" అంటే భోజనం లేదా అల్పాహారం తిన్న తరువాత.',
      },
    ],
  },

  // 2. TAMIL
  ta: {
    name: 'Tamil',
    nativeName: 'தமிழ்',
    kids: [
      {
        questionId: 'ta_k_1',
        type: 'multiple_choice',
        prompt: 'கீழ்கண்டவற்றில் முதல் தமிழ் உயிர் எழுத்து "அ" எது?',
        options: ['அ', 'க', 'ப', 'ம'],
        correctAnswer: 'அ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"அ" என்பது முதல் தமிழ் உயிர் எழுத்து (அம்மா).',
      },
      {
        questionId: 'ta_k_2',
        type: 'multiple_choice',
        prompt: '"ப - ல்" சேர்த்தால் என்ன சொல் உருவாகும்?',
        options: ['பல்', 'படம்', 'பட்டம்', 'பந்து'],
        correctAnswer: 'பல்',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"ப" + "ல்" = "பல்" (Tooth).',
      },
      {
        questionId: 'ta_k_3',
        type: 'multiple_choice',
        prompt: 'நமக்கு பால் தரும் விலங்கு எது?',
        options: ['பசு', 'புலி', 'சிங்கம்', 'காகம்'],
        correctAnswer: 'பசு',
        points: 20,
        skillCategory: 'reading',
        explanation: 'பசு நமக்கு பால் தருகிறது.',
      },
      {
        questionId: 'ta_k_4',
        type: 'reading_passage',
        passage: 'அன்பு பள்ளிக்குச் சென்றான். அவன் புதிய புத்தகம் படித்தான்.',
        prompt: 'அன்பு எதைப் படித்தான்?',
        options: ['புத்தகம்', 'செய்தி', 'விளம்பரம்', 'படம்'],
        correctAnswer: 'புத்தகம்',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'வாக்கியத்தில் "அவன் புதிய புத்தகம் படித்தான்" என்றுள்ளது.',
      },
      {
        questionId: 'ta_k_5',
        type: 'multiple_choice',
        prompt: '"அம்மா உணவு சமைத்தார்" - இதில் முதல் சொல் எது?',
        options: ['அம்மா', 'உணவு', 'சமைத்தார்', 'பள்ளி'],
        correctAnswer: 'அம்மா',
        points: 20,
        skillCategory: 'writing',
        explanation: 'வாக்கியத்தின் முதல் சொல் "அம்மா".',
      },
    ],
    teens: [
      {
        questionId: 'ta_t_1',
        type: 'multiple_choice',
        prompt: '"கல்வி" என்ற சொல்லில் உள்ள மெய்யெழுத்து எது?',
        options: ['ல்', 'க', 'வி', 'அ'],
        correctAnswer: 'ல்',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ல்" என்பது புள்ளி வைத்த மெய்யெழுத்து.',
      },
      {
        questionId: 'ta_t_2',
        type: 'multiple_choice',
        prompt: '"மாணவர்கள் நூலகத்தில் ________ படிக்கிறார்கள்."',
        options: ['நூல்கள்', 'தண்ணீர்', 'மரங்கள்', 'சாலையை'],
        correctAnswer: 'நூல்கள்',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'நூலகத்தில் நூல்கள் (புத்தகங்கள்) படிப்பார்கள்.',
      },
      {
        questionId: 'ta_t_3',
        type: 'multiple_choice',
        prompt: 'சரியான வாக்கிய அமைப்பைத் தேர்ந்தெடுக்கவும்:',
        options: [
          'சூரியன் கிழக்கில் உதிக்கிறது.',
          'உதிக்கிறது கிழக்கில் சூரியன்.',
          'சூரியன் இரவில் உதிக்கிறது.',
          'கிழக்கில் சந்திரன் உதிக்கிறது.',
        ],
        correctAnswer: 'சூரியன் கிழக்கில் உதிக்கிறது.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'இலக்கணப்படி சரியான வாக்கியம்: சூரியன் கிழக்கில் உதிக்கிறது.',
      },
      {
        questionId: 'ta_t_4',
        type: 'reading_passage',
        passage: 'மழைநீர் சேகரிப்பு நிலத்தடி நீர்மட்டத்தை உயர்த்தும் மிக முக்கியமான வழிமுறையாகும்.',
        prompt: 'மழைநீர் சேகரிப்பு எதை உயர்த்தும்?',
        options: ['நிலத்தடி நீர்மட்டம்', 'வெப்பநிலை', 'மாசுபாடு', 'காற்றழுத்தம்'],
        correctAnswer: 'நிலத்தடி நீர்மட்டம்',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'மழைநீர் சேகரிப்பு நிலத்தடி நீர்மட்டத்தை உயர்த்துகிறது.',
      },
      {
        questionId: 'ta_t_5',
        type: 'multiple_choice',
        prompt: '"நன்மை" என்பதன் எதிர்ச்சொல் எது?',
        options: ['தீமை', 'அன்பு', 'உண்மை', 'அமைதி'],
        correctAnswer: 'தீமை',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'நன்மை என்பதன் எதிர்ச்சொல் தீமை.',
      },
    ],
    adults: [
      {
        questionId: 'ta_a_1',
        type: 'multiple_choice',
        prompt: 'பேருந்து பலகையில் "சென்னை" என்ற சரியான எழுத்தைக் கண்டறியவும்:',
        options: ['சென்னை', 'சென்னைய்', 'செனை', 'செண்ணை'],
        correctAnswer: 'சென்னை',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'சரியான எழுத்துக்கூட்டல்: சென்னை.',
      },
      {
        questionId: 'ta_a_2',
        type: 'multiple_choice',
        prompt: 'மருத்துவமனையில் அவசர சிகிச்சை பிரிவை குறிக்கும் சொல் எது?',
        options: ['அவசர சிகிச்சை பிரிவு', 'உணவகம்', 'நூலகம்', 'பூங்கா'],
        correctAnswer: 'அவசர சிகிச்சை பிரிவு',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'அவசர மருத்துவ சேவை தரும் இடம் அவசர சிகிச்சை பிரிவு (Emergency).',
      },
      {
        questionId: 'ta_a_3',
        type: 'reading_passage',
        passage: 'மின்சாரக் கட்டணம் செலுத்த கடைசி நாள்: 20 ஏப்ரல் 2026. தாமதக் கட்டணம் ரூ. 40.',
        prompt: 'கட்டணம் செலுத்த கடைசி நாள் எது?',
        options: ['20 ஏப்ரல் 2026', '1 மே 2026', '15 மார்ச் 2026', '10 ஜூன் 2026'],
        correctAnswer: '20 ஏப்ரல் 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'அறிவிப்பில் கடைசி நாள் 20 ஏப்ரல் 2026 என்று குறிப்பிடப்பட்டுள்ளது.',
      },
      {
        questionId: 'ta_a_4',
        type: 'multiple_choice',
        prompt: 'வங்கி படிவத்தில் பணத்தை செலுத்துபவர் கையொப்பம் எங்கு இட வேண்டும்?',
        options: ['வாடிக்கையாளர் கையொப்பம் இடத்தில்', 'தேதி இடத்தில்', 'மேலாளர் கையொப்பத்தில்', 'தொகை இடத்தில்'],
        correctAnswer: 'வாடிக்கையாளர் கையொப்பம் இடத்தில்',
        points: 20,
        skillCategory: 'writing',
        explanation: 'வாடிக்கையாளர் கையொப்பம் (Customer Signature) பகுதியில் கையொப்பமிட வேண்டும்.',
      },
      {
        questionId: 'ta_a_5',
        type: 'multiple_choice',
        prompt: '"மருந்தை உணவுக்குப் பின் உட்கொள்ளவும்" - இதன் பொருள் என்ன?',
        options: [
          'சாப்பிட்ட பிறகு மருந்து சாப்பிட வேண்டும்',
          'வெறும் வயிற்றில் சாப்பிட வேண்டும்',
          'தூங்குவதற்கு முன் மட்டும் சாப்பிட வேண்டும்',
          'எப்போது வேண்டுமானாலும் சாப்பிடலாம்',
        ],
        correctAnswer: 'சாப்பிட்ட பிறகு மருந்து சாப்பிட வேண்டும்',
        points: 20,
        skillCategory: 'reading',
        explanation: '"உணவுக்குப் பின்" என்பது உணவு உண்ட பிறகு உட்கொள்வதைக் குறிக்கிறது.',
      },
    ],
  },

  // 3. KANNADA
  kn: {
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    kids: [
      {
        questionId: 'kn_k_1',
        type: 'multiple_choice',
        prompt: 'ಮೊದಲ ಕನ್ನಡ ಸ್ವರ "ಅ" (ಅಮ್ಮ) ಅಕ್ಷರವನ್ನು ಗುರುತಿಸಿ:',
        options: ['ಅ', 'ಕ', 'ರ', 'ಮ'],
        correctAnswer: 'ಅ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ಅ" ಮೊದಲ ಕನ್ನಡ ಸ್ವರಾಕ್ಷರವಾಗಿದೆ.',
      },
      {
        questionId: 'kn_k_2',
        type: 'multiple_choice',
        prompt: '"ಮ - ರ" ಸೇರಿಸಿದರೆ ಯಾವ ಪದವಾಗುತ್ತದೆ?',
        options: ['ಮರ', 'ಮನೆ', 'ಮಗು', 'ಮಣ್ಣು'],
        correctAnswer: 'ಮರ',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"ಮ" ಮತ್ತು "ರ" ಸೇರಿ "ಮರ" (Tree) ಆಗುತ್ತದೆ.',
      },
      {
        questionId: 'kn_k_3',
        type: 'multiple_choice',
        prompt: 'ನಮಗೆ ಹಾಲು ಕೊಡುವ ಪ್ರಾಣಿ ಯಾವುದು?',
        options: ['ಹಸು', 'ಹುಲಿ', 'ಸಿಂಹ', 'ಗಿಳಿ'],
        correctAnswer: 'ಹಸು',
        points: 20,
        skillCategory: 'reading',
        explanation: 'ಹಸು ನಮಗೆ ಸಿಹಿಯಾದ ಹಾಲನ್ನು ನೀಡುತ್ತದೆ.',
      },
      {
        questionId: 'kn_k_4',
        type: 'reading_passage',
        passage: 'ರಾಜು ಶಾಲೆಗೆ ಹೋದನು. ಅಲ್ಲಿ ಗೆಳೆಯರೊಂದಿಗೆ ಆಟವಾಡಿದನು ಮತ್ತು ಪುಸ್ತಕ ಓದಿದನು.',
        prompt: 'ರಾಜು ಎಲ್ಲಿಗೆ ಹೋದನು?',
        options: ['ಶಾಲೆಗೆ', 'ಮಾರುಕಟ್ಟೆಗೆ', 'ತೋಟಕ್ಕೆ', 'ಊರಿಗೆ'],
        correctAnswer: 'ಶಾಲೆಗೆ',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ವಾಕ್ಯದಲ್ಲಿ "ರಾಜು ಶಾಲೆಗೆ ಹೋದನು" ಎಂದು ಬರೆಯಲಾಗಿದೆ.',
      },
      {
        questionId: 'kn_k_5',
        type: 'multiple_choice',
        prompt: '"ಹಸು ಹುಲ್ಲು ತಿನ್ನುತ್ತದೆ" - ಈ ವಾಕ್ಯದ ಮೊದಲ ಪದ ಯಾವುದು?',
        options: ['ಹಸು', 'ಹುಲ್ಲು', 'ತಿನ್ನುತ್ತದೆ', 'ಹಾಲು'],
        correctAnswer: 'ಹಸು',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ವಾಕ್ಯದ ಮೊದಲ ಪದ "ಹಸು".',
      },
    ],
    teens: [
      {
        questionId: 'kn_t_1',
        type: 'multiple_choice',
        prompt: '"ಜ್ಞಾನ" ಪದದಲ್ಲಿರುವ ಸಂಯುಕ್ತಾಕ್ಷರ ಯಾವುದು?',
        options: ['ಜ್ಞ', 'ತ್ರ', 'ಶ್ರ', 'ಕ್ಷ'],
        correctAnswer: 'ಜ್ಞ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ಜ್ಞಾನ" ಪದದಲ್ಲಿ "ಜ್ಞ" ಒತ್ತು ಅಕ್ಷರವಿದೆ.',
      },
      {
        questionId: 'kn_t_2',
        type: 'multiple_choice',
        prompt: '"ವಿದ್ಯಾರ್ಥಿಗಳು ಗ್ರಂಥಾಲಯದಲ್ಲಿ ________ ಓದುತ್ತಾರೆ."',
        options: ['ಪುಸ್ತಕಗಳನ್ನು', 'ನೀರನ್ನು', 'ಗಿಡಗಳನ್ನು', 'ರಸ್ತೆಯನ್ನು'],
        correctAnswer: 'ಪುಸ್ತಕಗಳನ್ನು',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ಗ್ರಂಥಾಲಯದಲ್ಲಿ ಪುಸ್ತಕಗಳನ್ನು ಓದುತ್ತಾರೆ.',
      },
      {
        questionId: 'kn_t_3',
        type: 'multiple_choice',
        prompt: 'ಸರಿಯಾದ ವಾಕ್ಯ ರಚನೆಯನ್ನು ಆರಿಸಿ:',
        options: [
          'ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
          'ಹುಟ್ಟುತ್ತಾನೆ ಪೂರ್ವದಲ್ಲಿ ಸೂರ್ಯನು.',
          'ಸೂರ್ಯನು ಪಶ್ಚಿಮದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
          'ಪೂರ್ವದಲ್ಲಿ ರಾತ್ರಿ ಆಗುತ್ತದೆ.',
        ],
        correctAnswer: 'ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ವ್ಯಾಕರಣಬದ್ಧ ಸರಿಯಾದ ವಾಕ್ಯ: ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
      },
      {
        questionId: 'kn_t_4',
        type: 'reading_passage',
        passage: 'ಮರಗಳು ನಮಗೆ ಶುದ್ಧ ಗಾಳಿಯನ್ನು ನೀಡುತ್ತವೆ. ಪರಿಸರ ರಕ್ಷಣೆಗಾಗಿ ನಾವು ಗಿಡಗಳನ್ನು ಬೆಳೆಸಬೇಕು.',
        prompt: 'ಮರಗಳು ನಮಗೆ ಏನನ್ನು ನೀಡುತ್ತವೆ?',
        options: ['ಶುದ್ಧ ಗಾಳಿ (ಆಮ್ಲಜನಕ)', 'ಧೂಳು', 'ಶಬ್ದ ಮಾಲಿನ್ಯ', 'ಕಸ'],
        correctAnswer: 'ಶುದ್ಧ ಗಾಳಿ (ಆಮ್ಲಜನಕ)',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ಮರಗಳು ನಮಗೆ ಶುದ್ಧ ಗಾಳಿಯನ್ನು ಒದಗಿಸುತ್ತವೆ.',
      },
      {
        questionId: 'kn_t_5',
        type: 'multiple_choice',
        prompt: '"ಗೆಲುವು" ಪದದ ವಿರುದ್ಧ ಪದ ಯಾವುದು?',
        options: ['ಸೋಲು', 'ಖುಷಿ', 'ಉತ್ಸಾಹ', 'ಸಂತೋಷ'],
        correctAnswer: 'ಸೋಲು',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ಗೆಲುವು ಪದದ ವಿರುದ್ಧ ಪದ ಸೋಲು.',
      },
    ],
    adults: [
      {
        questionId: 'kn_a_1',
        type: 'multiple_choice',
        prompt: 'ಬಸ್ ಬೋರ್ಡ್‌ನಲ್ಲಿ "ಬೆಂಗಳೂರು" ಎಂದು ಬರೆದಿರುವ ಸರಿಯಾದ ರೂಪ ಯಾವುದು?',
        options: ['ಬೆಂಗಳೂರು', 'ಬೆಂಗಳೂರುರ', 'ಬೆಂಗಲೂರು', 'ಬೆಂಗಾಳೂರು'],
        correctAnswer: 'ಬೆಂಗಳೂರು',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'ಸರಿಯಾದ ಕಾಗುಣಿತ: ಬೆಂಗಳೂರು.',
      },
      {
        questionId: 'kn_a_2',
        type: 'multiple_choice',
        prompt: 'ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತುರ್ತು ಚಿಕಿತ್ಸೆ ನೀಡುವ ವಿಭಾಗ ಯಾವುದು?',
        options: ['ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ', 'ಉಪಹಾರ ಗೃಹ', 'ವಾಚನಾಲಯ', 'ಬಸ್ ನಿಲ್ದಾಣ'],
        correctAnswer: 'ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ತುರ್ತು ಸೇವೆ ನೀಡುವ ಸ್ಥಳ ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ (Emergency).',
      },
      {
        questionId: 'kn_a_3',
        type: 'reading_passage',
        passage: 'ವಿದ್ಯುತ್ ಬಿಲ್ ಪಾವತಿಸಲು ಕೊನೆಯ ದಿನಾಂಕ: 22 ಮಾರ್ಚ್ 2026. ವಿಳಂಬ ಶುಲ್ಕ ರೂ. 45.',
        prompt: 'ಬಿಲ್ ಪಾವತಿಸಲು ಕೊನೆಯ ದಿನಾಂಕ ಯಾವುದು?',
        options: ['22 ಮಾರ್ಚ್ 2026', '1 ಏಪ್ರಿಲ್ 2026', '10 ಮೇ 2026', '5 ಜನವರಿ 2026'],
        correctAnswer: '22 ಮಾರ್ಚ್ 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ಸೂಚನೆಯಲ್ಲಿ ಕೊನೆಯ ದಿನಾಂಕ 22 ಮಾರ್ಚ್ 2026 ಎಂದು ನಮೂದಿಸಲಾಗಿದೆ.',
      },
      {
        questionId: 'kn_a_4',
        type: 'multiple_choice',
        prompt: 'ಬ್ಯಾಂಕ್ ಚಲನ್‌ನಲ್ಲಿ ಠೇವಣಿದಾರರ ಸಹಿಯನ್ನು ಎಲ್ಲಿ ಮಾಡಬೇಕು?',
        options: ['ಠೇವಣಿದಾರರ ಸಹಿ ಜಾಗದಲ್ಲಿ', 'ದಿನಾಂಕದ ಮೇಲೆ', 'ಮೊತ್ತದ ಮೇಲೆ', 'ಮ್ಯಾನೇಜರ್ ಸ್ಥಾನದಲ್ಲಿ'],
        correctAnswer: 'ಠೇವಣಿದಾರರ ಸಹಿ ಜಾಗದಲ್ಲಿ',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ಗ್ರಾಹಕರ ಸಹಿ (Depositor Signature) ಇರುವ ಸ್ಥಳದಲ್ಲಿ ಸಹಿ ಮಾಡಬೇಕು.',
      },
      {
        questionId: 'kn_a_5',
        type: 'multiple_choice',
        prompt: '"ಔಷಧಿಯನ್ನು ಊಟದ ನಂತರ ಸೇವಿಸಿ" - ಇದರ ಅರ್ಥವೇನು?',
        options: [
          'ಊಟ ಮಾಡಿದ ನಂತರ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಮಲಗುವ ಮುನ್ನ ಮಾತ್ರ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಯಾವಾಗಲಾದರೂ ತೆಗೆದುಕೊಳ್ಳಬಹುದು',
        ],
        correctAnswer: 'ಊಟ ಮಾಡಿದ ನಂತರ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
        points: 20,
        skillCategory: 'reading',
        explanation: '"ಊಟದ ನಂತರ" ಎಂದರೆ ಊಟ ಮಾಡಿದ ಬಳಿಕ ಔಷಧ ಸೇವಿಸುವುದು.',
      },
    ],
  },

  // 4. MALAYALAM
  ml: {
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    kids: [
      {
        questionId: 'ml_k_1',
        type: 'multiple_choice',
        prompt: 'താഴെ പറയുന്നവയിൽ ആദ്യത്തെ മലയാളം സ്വരാക്ഷരം "അ" (അമ്മ) ഏതാണ്?',
        options: ['അ', 'ക', 'പ', 'മ'],
        correctAnswer: 'അ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"അ" ആദ്യത്തെ മലയാളം സ്വരാക്ഷരമാണ് (അമ്മ).',
      },
      {
        questionId: 'ml_k_2',
        type: 'multiple_choice',
        prompt: '"മ - രം" ചേർത്താൽ ഏത് വാക്കാണ് ലഭിക്കുന്നത്?',
        options: ['മരം', 'മനസ്സ്', 'മണ്ണ്', 'മഴ'],
        correctAnswer: 'മരം',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"മ" + "രം" = "മരം" (Tree).',
      },
      {
        questionId: 'ml_k_3',
        type: 'multiple_choice',
        prompt: 'നമുക്ക് പാൽ നൽകുന്ന മൃഗം ഏതാണ്?',
        options: ['പശു', 'കടുവ', 'സിംഹം', 'കാക്ക'],
        correctAnswer: 'പശു',
        points: 20,
        skillCategory: 'reading',
        explanation: 'പശു നമുക്ക് ശുദ്ധമായ പാൽ തരുന്നു.',
      },
      {
        questionId: 'ml_k_4',
        type: 'reading_passage',
        passage: 'അപ്പു സ്കൂളിൽ പോയി. അവൻ പുതിയ പുസ്തകം വായിച്ചു.',
        prompt: 'അപ്പു എന്താണ് വായിച്ചത്?',
        options: ['പുസ്തകം', 'വാർത്ത', 'ചിത്രം', 'പത്രം'],
        correctAnswer: 'പുസ്തകം',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'വാക്യത്തിൽ "അവൻ പുതിയ പുസ്തകം വായിച്ചു" എന്ന് പറയുന്നു.',
      },
      {
        questionId: 'ml_k_5',
        type: 'multiple_choice',
        prompt: '"അമ്മ ഭക്ഷണം ഉണ്ടാക്കി" - ഇതിലെ ആദ്യത്തെ വാക്ക് ഏതാണ്?',
        options: ['അമ്മ', 'ഭക്ഷണം', 'ഉണ്ടാക്കി', 'സ്കൂൾ'],
        correctAnswer: 'അമ്മ',
        points: 20,
        skillCategory: 'writing',
        explanation: 'വാക്യത്തിലെ ആദ്യത്തെ വാക്ക് "അമ്മ".',
      },
    ],
    teens: [
      {
        questionId: 'ml_t_1',
        type: 'multiple_choice',
        prompt: '"വിദ്യ" എന്ന വാക്കിലെ കൂട്ടക്ഷരം ഏതാണ്?',
        options: ['ദ്യ', 'ശ്ര', 'ത്ര', 'ക്ഷ'],
        correctAnswer: 'ദ്യ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"വിദ്യ" എന്ന വാക്കിൽ "ദ്യ" കൂട്ടക്ഷരമാണ്.',
      },
      {
        questionId: 'ml_t_2',
        type: 'multiple_choice',
        prompt: '"വിദ്യാർത്ഥികൾ ലൈബ്രറിയിൽ ________ വായിക്കുന്നു."',
        options: ['പുസ്തകങ്ങൾ', 'വെള്ളം', 'മരങ്ങൾ', 'വഴികൾ'],
        correctAnswer: 'പുസ്തകങ്ങൾ',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ലൈബ്രറിയിൽ പുസ്തകങ്ങൾ വായിക്കുന്നു.',
      },
      {
        questionId: 'ml_t_3',
        type: 'multiple_choice',
        prompt: 'ശരിയായ വാക്യം തിരഞ്ഞെടുക്കുക:',
        options: [
          'സൂര്യൻ കിഴക്ക് ഉദിക്കുന്നു.',
          'ഉദിക്കുന്നു കിഴക്ക് സൂര്യൻ.',
          'സൂര്യൻ രാത്രിയിൽ ഉദിക്കുന്നു.',
          'കിഴക്ക് ചന്ദ്രൻ ഉദിക്കുന്നു.',
        ],
        correctAnswer: 'സൂര്യൻ കിഴക്ക് ഉദിക്കുന്നു.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'വ്യാകരണപരമായി ശരിയായ വാക്യം: സൂര്യൻ കിഴക്ക് ഉദിക്കുന്നു.',
      },
      {
        questionId: 'ml_t_4',
        type: 'reading_passage',
        passage: 'മരങ്ങൾ നമുക്ക് ശുദ്ധവായു നൽകുന്നു. പരിസ്ഥിതി സംരക്ഷണത്തിനായി നാം വൃക്ഷത്തൈകൾ നടണം.',
        prompt: 'മരങ്ങൾ നമുക്ക് എന്ത് നൽകുന്നു?',
        options: ['ശുദ്ധവായു (ഓക്സിജൻ)', 'പുക', 'ശബ്ദമലിനീകരണം', 'മാലിന്യം'],
        correctAnswer: 'ശുദ്ധവായു (ഓക്സിജൻ)',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'മരങ്ങൾ നമുക്ക് ശുദ്ധവായു നൽകുന്നു.',
      },
      {
        questionId: 'ml_t_5',
        type: 'multiple_choice',
        prompt: '"വിജയം" എന്ന വാക്കിന്റെ വിപരീതപദം ഏതാണ്?',
        options: ['പരാജയം', 'സന്തോഷം', 'ആഹ്ലാദം', 'ഉത്സാഹം'],
        correctAnswer: 'പരാജയം',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'വിജയത്തിന്റെ വിപരീതപദം പരാജയം.',
      },
    ],
    adults: [
      {
        questionId: 'ml_a_1',
        type: 'multiple_choice',
        prompt: 'ബസ് ബോർഡിൽ "തിരുവനന്തപുരം" എന്ന് എഴുതിയിരിക്കുന്ന ശരിയായ രൂപം ഏതാണ്?',
        options: ['തിരുവനന്തപുരം', 'തിരുവനതപുരം', 'തിരുവേന്തപുരം', 'തിരുവനന്തപുരംരം'],
        correctAnswer: 'തിരുവനന്തപുരം',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'ശരിയായ അക്ഷരവിന്യാസം: തിരുവനന്തപുരം.',
      },
      {
        questionId: 'ml_a_2',
        type: 'multiple_choice',
        prompt: 'ആശുപത്രിയിൽ അടിയന്തിര ചികിത്സ നൽകുന്ന വിഭാഗം ഏതാണ്?',
        options: ['കാഷ്വാലിറ്റി / അടിയന്തിര വിഭാഗം', 'ഭക്ഷണശാല', 'വായനശാല', 'ടിക്കറ്റ് കൗണ്ടർ'],
        correctAnswer: 'കാഷ്വാലിറ്റി / അടിയന്തിര വിഭാഗം',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'അടിയന്തിര ചികിത്സ നൽകുന്ന സ്ഥലം കാഷ്വാലിറ്റി (Emergency).',
      },
      {
        questionId: 'ml_a_3',
        type: 'reading_passage',
        passage: 'വൈദ്യുതി ബിൽ അടയ്ക്കാനുള്ള അവസാന തീയതി: 28 മാർച്ച് 2026. പിഴ തുക: ₹50.',
        prompt: 'ബിൽ അടയ്ക്കാനുള്ള അവസാന തീയതി ഏതാണ്?',
        options: ['28 മാർച്ച് 2026', '1 ഏപ്രിൽ 2026', '15 മെയ് 2026', '10 ജൂൺ 2026'],
        correctAnswer: '28 മാർച്ച് 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'അറിയിപ്പിൽ അവസാന തീയതി 28 മാർച്ച് 2026 എന്ന് വ്യക്തമാക്കിയിട്ടുണ്ട്.',
      },
      {
        questionId: 'ml_a_4',
        type: 'multiple_choice',
        prompt: 'ബാങ്ക് ഫോമിൽ പണം നിക്ഷേപിക്കുന്നയാൾ ഒപ്പ് എവിടെ രേഖപ്പെടുത്തണം?',
        options: ['നിക്ഷേപകന്റെ ഒപ്പ് ഉള്ളിടത്ത്', 'തീയതിയിൽ', 'തുകയുടെ മുകളിൽ', 'മാനേജറുടെ സ്ഥാനത്ത്'],
        correctAnswer: 'നിക്ഷേപകന്റെ ഒപ്പ് ഉള്ളിടത്ത്',
        points: 20,
        skillCategory: 'writing',
        explanation: 'നിക്ഷേപകന്റെ ഒപ്പ് (Depositor Signature) ഉള്ളിടത്ത് ഒപ്പിടണം.',
      },
      {
        questionId: 'ml_a_5',
        type: 'multiple_choice',
        prompt: '"മരുന്ന് ഭക്ഷണത്തിന് ശേഷം കഴിക്കുക" - ഇതിന്റെ അർത്ഥം എന്താണ്?',
        options: [
          'ഭക്ഷണം കഴിച്ച ശേഷം മരുന്ന് കഴിക്കണം',
          'വെറും വയറ്റിൽ കഴിക്കണം',
          'ഉറങ്ങുന്നതിന് തൊട്ടുമുമ്പ് മാത്രം കഴിക്കണം',
          'എപ്പോൾ വേണമെങ്കിലും കഴിക്കാം',
        ],
        correctAnswer: 'ഭക്ഷണം കഴിച്ച ശേഷം മരുന്ന് കഴിക്കണം',
        points: 20,
        skillCategory: 'reading',
        explanation: '"ഭക്ഷണത്തിന് ശേഷം" എന്നാൽ ഭക്ഷണം കഴിച്ചതിന് ശേഷം കഴിക്കുക.',
      },
    ],
  },

  // 5. HINDI
  hi: {
    name: 'Hindi',
    nativeName: 'हिंदी',
    kids: [
      {
        questionId: 'hi_k_1',
        type: 'multiple_choice',
        prompt: 'नीचे दिए गए अक्षरों में से पहला स्वर "अ" (अनार) कौन सा है?',
        options: ['अ', 'क', 'म', 'र'],
        correctAnswer: 'अ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"अ" देवनागरी वर्णमाला का पहला स्वर है।',
      },
      {
        questionId: 'hi_k_2',
        type: 'multiple_choice',
        prompt: '"क - ल - म" को मिलाने पर कौन सा शब्द बनता है?',
        options: ['कलम', 'कमल', 'कसरत', 'कलश'],
        correctAnswer: 'कलम',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"क" + "ल" + "म" = कलम (Pen).',
      },
      {
        questionId: 'hi_k_3',
        type: 'multiple_choice',
        prompt: 'दूध देने वाला जानवर कौन सा है?',
        options: ['गाय', 'शेर', 'चीता', 'कौआ'],
        correctAnswer: 'गाय',
        points: 20,
        skillCategory: 'reading',
        explanation: 'गाय हमें मीठा दूध देती है।',
      },
      {
        questionId: 'hi_k_4',
        type: 'reading_passage',
        passage: 'रोहन स्कूल गया। उसने दोस्तों के साथ खेला और एक नई किताब पढ़ी।',
        prompt: 'रोहन ने क्या पढ़ा?',
        options: ['किताब', 'अखबार', 'बोर्ड', 'संदेश'],
        correctAnswer: 'किताब',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'कहानी में लिखा है कि रोहन ने किताब पढ़ी।',
      },
      {
        questionId: 'hi_k_5',
        type: 'multiple_choice',
        prompt: '"गाय घास खाती है" - इस वाक्य का पहला शब्द कौन सा है?',
        options: ['गाय', 'घास', 'खाती', 'है'],
        correctAnswer: 'गाय',
        points: 20,
        skillCategory: 'writing',
        explanation: 'वाक्य का पहला शब्द "गाय" है।',
      },
    ],
    teens: [
      {
        questionId: 'hi_t_1',
        type: 'multiple_choice',
        prompt: '"ज्ञान" शब्द में संयुक्त व्यंजन कौन सा है?',
        options: ['ज्ञ', 'त्र', 'श्र', 'क्ष'],
        correctAnswer: 'ज्ञ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ज्ञान" में "ज्ञ" संयुक्त व्यंजन है।',
      },
      {
        questionId: 'hi_t_2',
        type: 'multiple_choice',
        prompt: '"विद्यार्थी पुस्तकालय में ________ पढ़ते हैं।"',
        options: ['किताबें', 'पानी', 'पेड़', 'सड़क'],
        correctAnswer: 'किताबें',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'पुस्तकालय में किताबें पढ़ी जाती हैं।',
      },
      {
        questionId: 'hi_t_3',
        type: 'multiple_choice',
        prompt: 'सही वाक्य संरचना चुनिए:',
        options: [
          'सूरज पूर्व दिशा में उगता है।',
          'उगता है पूर्व में सूरज।',
          'सूरज रात में उगता है।',
          'पूर्व में चांद उगता है दिन में।',
        ],
        correctAnswer: 'सूरज पूर्व दिशा में उगता है।',
        points: 20,
        skillCategory: 'writing',
        explanation: 'व्याकरण की दृष्टि से शुद्ध वाक्य: सूरज पूर्व दिशा में उगता है।',
      },
      {
        questionId: 'hi_t_4',
        type: 'reading_passage',
        passage: 'पेड़ हमें शुद्ध प्राणवायु (ऑक्सीजन) देते हैं। पर्यावरण को स्वच्छ रखने के लिए हमें अधिक पेड़ लगाने चाहिए।',
        prompt: 'पेड़ हमें क्या प्रदान करते हैं?',
        options: ['शुद्ध प्राणवायु (ऑक्सीजन)', 'धुआं', 'कचरा', 'प्रदूषण'],
        correctAnswer: 'शुद्ध प्राणवायु (ऑक्सीजन)',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'पेड़ हमें ऑक्सीजन देते हैं।',
      },
      {
        questionId: 'hi_t_5',
        type: 'multiple_choice',
        prompt: '"सफलता" शब्द का विलोम शब्द क्या है?',
        options: ['असफलता', 'विजय', 'हर्ष', 'उल्लास'],
        correctAnswer: 'असफलता',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'सफलता का विलोम असफलता होता है।',
      },
    ],
    adults: [
      {
        questionId: 'hi_a_1',
        type: 'multiple_choice',
        prompt: 'बस के बोर्ड पर "दिल्ली" लिखा हुआ सही रूप कौन सा है?',
        options: ['दिल्ली', 'दिलि', 'दील्ली', 'दिल्लि'],
        correctAnswer: 'दिल्ली',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'सही वर्तनी: दिल्ली।',
      },
      {
        questionId: 'hi_a_2',
        type: 'multiple_choice',
        prompt: 'अस्पताल में आपातकालीन चिकित्सा देने वाला विभाग कौन सा है?',
        options: ['आपातकालीन चिकित्सा विभाग (Emergency)', 'कैंटीन', 'वाचनालय', 'टिकट घर'],
        correctAnswer: 'आपातकालीन चिकित्सा विभाग (Emergency)',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'गंभीर स्थिति में आपातकालीन विभाग में उपचार होता है।',
      },
      {
        questionId: 'hi_a_3',
        type: 'reading_passage',
        passage: 'बिजली बिल जमा करने की अंतिम तिथि: 25 मार्च 2026 है। इसके बाद ₹50 विलंब शुल्क देय होगा।',
        prompt: 'बिल भरने की अंतिम तारीख क्या है?',
        options: ['25 मार्च 2026', '1 अप्रैल 2026', '10 मई 2026', '15 जनवरी 2026'],
        correctAnswer: '25 मार्च 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'सूचना में अंतिम तिथि 25 मार्च 2026 दी गई है।',
      },
      {
        questionId: 'hi_a_4',
        type: 'multiple_choice',
        prompt: 'बैंक में पैसे जमा करने वाले फॉर्म पर अपने हस्ताक्षर कहाँ करने चाहिए?',
        options: ['जमाकर्ता के हस्ताक्षर वाले स्थान पर', 'तारीख के ऊपर', 'बैंक की मुहर पर', 'प्रबंधक के स्थान पर'],
        correctAnswer: 'जमाकर्ता के हस्ताक्षर वाले स्थान पर',
        points: 20,
        skillCategory: 'writing',
        explanation: 'जमाकर्ता (Depositor) के हस्ताक्षर के स्थान पर ही दस्तखत करें।',
      },
      {
        questionId: 'hi_a_5',
        type: 'multiple_choice',
        prompt: '"दवा भोजन के बाद ही लें" - इसका क्या तात्पर्य है?',
        options: [
          'खाना खाने के बाद दवा खानी है',
          'खाली पेट दवा खानी है',
          'केवल सोने से पहले खानी है',
          'कभी भी खा सकते हैं',
        ],
        correctAnswer: 'खाना खाने के बाद दवा खानी है',
        points: 20,
        skillCategory: 'reading',
        explanation: '"भोजन के बाद" का अर्थ है भोजन करने के उपरांत।',
      },
    ],
  },

  // 6. ENGLISH
  en: {
    name: 'English',
    nativeName: 'English',
    kids: [
      {
        questionId: 'en_k_1',
        type: 'multiple_choice',
        prompt: 'Which letter matches the beginning sound of the word "Apple"?',
        options: ['A', 'B', 'C', 'D'],
        correctAnswer: 'A',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'Apple begins with the letter "A".',
      },
      {
        questionId: 'en_k_2',
        type: 'multiple_choice',
        prompt: 'Combine the letters: "C - A - T". What word is formed?',
        options: ['Cat', 'Car', 'Cap', 'Cup'],
        correctAnswer: 'Cat',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'C + A + T forms the word "Cat".',
      },
      {
        questionId: 'en_k_3',
        type: 'multiple_choice',
        prompt: 'Which animal gives us milk?',
        options: ['Cow', 'Tiger', 'Lion', 'Crow'],
        correctAnswer: 'Cow',
        points: 20,
        skillCategory: 'reading',
        explanation: 'A cow gives us fresh milk.',
      },
      {
        questionId: 'en_k_4',
        type: 'reading_passage',
        passage: 'Sam went to school. He played with his friends and read a colorful storybook.',
        prompt: 'What did Sam read at school?',
        options: ['A storybook', 'A newspaper', 'A letter', 'A billboard'],
        correctAnswer: 'A storybook',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'The passage mentions Sam read a colorful storybook.',
      },
      {
        questionId: 'en_k_5',
        type: 'multiple_choice',
        prompt: '"The cow eats green grass" - What is the first word in this sentence?',
        options: ['The', 'cow', 'eats', 'grass'],
        correctAnswer: 'The',
        points: 20,
        skillCategory: 'writing',
        explanation: '"The" is the first word of the sentence.',
      },
    ],
    teens: [
      {
        questionId: 'en_t_1',
        type: 'multiple_choice',
        prompt: 'Identify the word with the correct spelling:',
        options: ['Knowledge', 'Knowlege', 'Nowledge', 'Knolege'],
        correctAnswer: 'Knowledge',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'The correct English spelling is "Knowledge".',
      },
      {
        questionId: 'en_t_2',
        type: 'multiple_choice',
        prompt: 'Complete the sentence: "Students visit the library to read ________."',
        options: ['books', 'water', 'trees', 'roads'],
        correctAnswer: 'books',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'Books are read in the library.',
      },
      {
        questionId: 'en_t_3',
        type: 'multiple_choice',
        prompt: 'Choose the grammatically correct sentence:',
        options: [
          'The sun rises in the east.',
          'Rises the sun in the east.',
          'The sun rise on east.',
          'In east rises sun the.',
        ],
        correctAnswer: 'The sun rises in the east.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'Standard English syntax: Subject + Verb + Prepositional phrase.',
      },
      {
        questionId: 'en_t_4',
        type: 'reading_passage',
        passage: 'Trees provide us with fresh oxygen and absorb carbon dioxide. Planting saplings protects our climate.',
        prompt: 'What essential gas do trees provide for humans?',
        options: ['Oxygen', 'Smoke', 'Dust', 'Pollution'],
        correctAnswer: 'Oxygen',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'Trees provide us with fresh oxygen.',
      },
      {
        questionId: 'en_t_5',
        type: 'multiple_choice',
        prompt: 'What is the opposite (antonym) of the word "Success"?',
        options: ['Failure', 'Victory', 'Happiness', 'Joy'],
        correctAnswer: 'Failure',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'Failure is the opposite of success.',
      },
    ],
    adults: [
      {
        questionId: 'en_a_1',
        type: 'multiple_choice',
        prompt: 'Identify the correct signboard spelling for the city:',
        options: ['Bengaluru', 'Bengalore', 'Bengluru', 'Bangaluruu'],
        correctAnswer: 'Bengaluru',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'The official city spelling is Bengaluru.',
      },
      {
        questionId: 'en_a_2',
        type: 'multiple_choice',
        prompt: 'Which department in a hospital provides urgent immediate medical care?',
        options: ['Emergency / Casualty', 'Cafeteria', 'Library', 'Ticket Counter'],
        correctAnswer: 'Emergency / Casualty',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'Immediate urgent care is provided in the Emergency department.',
      },
      {
        questionId: 'en_a_3',
        type: 'reading_passage',
        passage: 'Electricity Bill Due Date: 25th March 2026. A late payment fee of ₹50 applies thereafter.',
        prompt: 'What is the deadline for bill payment without penalty?',
        options: ['25th March 2026', '1st April 2026', '10th May 2026', '15th January 2026'],
        correctAnswer: '25th March 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'The notice explicitly states 25th March 2026.',
      },
      {
        questionId: 'en_a_4',
        type: 'multiple_choice',
        prompt: 'Where should you sign on a bank deposit slip?',
        options: ['At Depositor Signature', 'Above the Date', 'Over the Bank Stamp', 'At Branch Manager space'],
        correctAnswer: 'At Depositor Signature',
        points: 20,
        skillCategory: 'writing',
        explanation: 'The depositor signs in the designated Depositor Signature section.',
      },
      {
        questionId: 'en_a_5',
        type: 'multiple_choice',
        prompt: '"Take one tablet after meals" - What does this prescription instruction mean?',
        options: [
          'Take the medicine after having food',
          'Take the medicine on an empty stomach',
          'Take only right before sleeping',
          'Take at any random time',
        ],
        correctAnswer: 'Take the medicine after having food',
        points: 20,
        skillCategory: 'reading',
        explanation: '"After meals" means taking it following breakfast, lunch, or dinner.',
      },
    ],
  },

  // 7. BENGALI
  bn: {
    name: 'Bengali',
    nativeName: 'বাংলা',
    kids: [
      {
        questionId: 'bn_k_1',
        type: 'multiple_choice',
        prompt: 'নিচের বর্ণগুলির মধ্যে প্রথম স্বরবর্ণ "অ" (অজগর) কোনটি?',
        options: ['অ', 'ক', 'ম', 'র'],
        correctAnswer: 'অ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"অ" হলো বাংলা বর্ণমালার প্রথম স্বরবর্ণ।',
      },
      {
        questionId: 'bn_k_2',
        type: 'multiple_choice',
        prompt: '"ক - ল - ম" যুক্ত করলে কোন শব্দটি গঠিত হয়?',
        options: ['কলম', 'কমল', 'জল', 'বই'],
        correctAnswer: 'কলম',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"ক" + "ল" + "ম" = কলম (Pen).',
      },
      {
        questionId: 'bn_k_3',
        type: 'multiple_choice',
        prompt: 'আমাদের দুধ দেয় কোন প্রাণী?',
        options: ['গরু', 'বাঘ', 'সিংহ', 'কাক'],
        correctAnswer: 'গরু',
        points: 20,
        skillCategory: 'reading',
        explanation: 'গরু আমাদের পুষ্টিকর দুধ দেয়।',
      },
      {
        questionId: 'bn_k_4',
        type: 'reading_passage',
        passage: 'রবি স্কুলে গেল। সে বন্ধুদের সাথে খেলা করল এবং নতুন গল্পের বই পড়ল।',
        prompt: 'রবি কী পড়ল?',
        options: ['গল্পের বই', 'সংবাদপত্র', 'বিজ্ঞাপন', 'চিঠি'],
        correctAnswer: 'গল্পের বই',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'অনুচ্ছেদে উল্লেখ আছে যে রবি গল্পের বই পড়ল।',
      },
      {
        questionId: 'bn_k_5',
        type: 'multiple_choice',
        prompt: '"গরু ঘাস খায়" - এই বাক্যের প্রথম শব্দটি কী?',
        options: ['গরু', 'ঘাস', 'খায়', 'দুধ'],
        correctAnswer: 'গরু',
        points: 20,
        skillCategory: 'writing',
        explanation: 'বাক্যের প্রথম শব্দ হলো "গরু"।',
      },
    ],
    teens: [
      {
        questionId: 'bn_t_1',
        type: 'multiple_choice',
        prompt: '"জ্ঞান" শব্দটিতে কোন যুক্তাক্ষর রয়েছে?',
        options: ['জ্ঞ', 'ত্র', 'শ্র', 'ক্ষ'],
        correctAnswer: 'জ্ঞ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"জ্ঞান" শব্দে "জ্ঞ" যুক্তাক্ষর রয়েছে।',
      },
      {
        questionId: 'bn_t_2',
        type: 'multiple_choice',
        prompt: '"শিক্ষার্থীরা গ্রন্থাগারে ________ পড়ছে।"',
        options: ['বই', 'জল', 'গাছপালা', 'রাস্তা'],
        correctAnswer: 'বই',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'গ্রন্থাগারে বই পড়া হয়।',
      },
      {
        questionId: 'bn_t_3',
        type: 'multiple_choice',
        prompt: 'সঠিক বাক্য গঠনটি নির্বাচন করুন:',
        options: [
          'সূর্য পূর্ব দিকে উদিত হয়।',
          'উদিত হয় পূর্বে সূর্য।',
          'সূর্য রাতে উদিত হয়।',
          'পূর্বে রাতে চাঁদ ওঠে।',
        ],
        correctAnswer: 'সূর্য পূর্ব দিকে উদিত হয়।',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ব্যাকরণগতভাবে সঠিক বাক্য: সূর্য পূর্ব দিকে উদিত হয়।',
      },
      {
        questionId: 'bn_t_4',
        type: 'reading_passage',
        passage: 'গাছ আমাদের বিশুদ্ধ অক্সিজেন দেয়। পরিবেশ সুরক্ষায় আমাদের বেশি করে বৃক্ষরোপণ করা উচিত।',
        prompt: 'গাছ আমাদের কী প্রদান করে?',
        options: ['বিশুদ্ধ অক্সিজেন', 'ধোঁয়া', 'আবর্জনা', 'শব্দদূষণ'],
        correctAnswer: 'বিশুদ্ধ অক্সিজেন',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'গাছ আমাদের বিশুদ্ধ অক্সিজেন সরবরাহ করে।',
      },
      {
        questionId: 'bn_t_5',
        type: 'multiple_choice',
        prompt: '"সাফল্য" শব্দের বিপরীত শব্দ কী?',
        options: ['ব্যর্থতা', 'জয়', 'আনন্দ', 'উল্লাস'],
        correctAnswer: 'ব্যর্থতা',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'সাফল্যের বিপরীত শব্দ ব্যর্থতা।',
      },
    ],
    adults: [
      {
        questionId: 'bn_a_1',
        type: 'multiple_choice',
        prompt: 'বাসের বোর্ডে "কলকাতা" লেখা সঠিক বানানটি শনাক্ত করুন:',
        options: ['কলকাতা', 'কলিকাতা', 'কলকতা', 'কুলকাতা'],
        correctAnswer: 'কলকাতা',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'সঠিক বানান: কলকাতা।',
      },
      {
        questionId: 'bn_a_2',
        type: 'multiple_choice',
        prompt: 'হাসপাতালে জরুরি চিকিৎসার জন্য কোন বিভাগে যেতে হয়?',
        options: ['জরুরি বিভাগ (Emergency)', 'ক্যান্টিন', 'পাঠাগার', 'টিকিট ঘর'],
        correctAnswer: 'জরুরি বিভাগ (Emergency)',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'জরুরি চিকিৎসার জন্য জরুরি বিভাগ নির্ধারিত।',
      },
      {
        questionId: 'bn_a_3',
        type: 'reading_passage',
        passage: 'বিদ্যুৎ বিল জমা দেওয়ার শেষ তারিখ: ২৫ মার্চ ২০২৬। বিলম্ব ফি ₹৫০ ধার্য করা হবে।',
        prompt: 'বিল জমা দেওয়ার শেষ তারিখ কোনটি?',
        options: ['২৫ মার্চ ২০২৬', '১ এপ্রিল ২০২৬', '১০ মে ২০২৬', '১৫ জানুয়ারি ২০২৬'],
        correctAnswer: '২৫ মার্চ ২০২৬',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'বিজ্ঞপ্তিতে শেষ তারিখ ২৫ মার্চ ২০২৬ উল্লেখ আছে।',
      },
      {
        questionId: 'bn_a_4',
        type: 'multiple_choice',
        prompt: 'ব্যাংকের জমা স্লিপে নিজের স্বাক্ষর কোথায় করতে হবে?',
        options: ['জমা প্রদানকারীর স্বাক্ষর স্থানে', 'তারিখের উপরে', 'ব্যাংকের সিলের উপর', 'ম্যানেজারের স্থানে'],
        correctAnswer: 'জমা প্রদানকারীর স্বাক্ষর স্থানে',
        points: 20,
        skillCategory: 'writing',
        explanation: 'জমা প্রদানকারীর স্বাক্ষর (Depositor Signature) স্থানে স্বাক্ষর করতে হবে।',
      },
      {
        questionId: 'bn_a_5',
        type: 'multiple_choice',
        prompt: '"খাওয়ার পর ওষুধ সেবন করুন" - এর অর্থ কী?',
        options: [
          'খাবার খাওয়ার পরে ওষুধ খেতে হবে',
          'খালি পেটে খেতে হবে',
          'ঘুমোনোর ঠিক আগে খেতে হবে',
          'যেকোনো সময় খাওয়া যাবে',
        ],
        correctAnswer: 'খাবার খাওয়ার পরে ওষুধ খেতে হবে',
        points: 20,
        skillCategory: 'reading',
        explanation: '"খাওয়ার পর" মানে আহার গ্রহণের পর।',
      },
    ],
  },

  // 8. MARATHI
  mr: {
    name: 'Marathi',
    nativeName: 'मराठी',
    kids: [
      {
        questionId: 'mr_k_1',
        type: 'multiple_choice',
        prompt: 'खालीलपैकी पहिला स्वर "अ" (अननस) कोणता आहे?',
        options: ['अ', 'क', 'म', 'र'],
        correctAnswer: 'अ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"अ" हा मराठी वर्णमालेतील पहिला स्वर आहे.',
      },
      {
        questionId: 'mr_k_2',
        type: 'multiple_choice',
        prompt: '"क - प" एकत्र केल्यास कोणता शब्द तयार होतो?',
        options: ['कप', 'कमळ', 'कपाट', 'कलम'],
        correctAnswer: 'कप',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"क" + "प" = कप (Cup).',
      },
      {
        questionId: 'mr_k_3',
        type: 'multiple_choice',
        prompt: 'आपल्याला दूध देणारा प्राणी कोणता?',
        options: ['गाय', 'वाघ', 'सिंह', 'कावळा'],
        correctAnswer: 'गाय',
        points: 20,
        skillCategory: 'reading',
        explanation: 'गाय आपल्याला दूध देते.',
      },
      {
        questionId: 'mr_k_4',
        type: 'reading_passage',
        passage: 'रोहन शाळेत गेला. त्याने मित्रांसोबत खेळ केला आणि नवीन गोष्टीचे पुस्तक वाचले.',
        prompt: 'रोहनने काय वाचले?',
        options: ['गोष्टीचे पुस्तक', 'वर्तमानपत्र', 'पाटी', 'संदेश'],
        correctAnswer: 'गोष्टीचे पुस्तक',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'उताऱ्यात नमूद आहे की रोहनने गोष्टीचे पुस्तक वाचले.',
      },
      {
        questionId: 'mr_k_5',
        type: 'multiple_choice',
        prompt: '"गाय गवत खाते" - या वाक्यातील पहिला शब्द कोणता?',
        options: ['गाय', 'गवत', 'खाते', 'दूध'],
        correctAnswer: 'गाय',
        points: 20,
        skillCategory: 'writing',
        explanation: 'वाक्यातील पहिला शब्द "गाय" आहे.',
      },
    ],
    teens: [
      {
        questionId: 'mr_t_1',
        type: 'multiple_choice',
        prompt: '"ज्ञान" या शब्दात कोणते जोडाक्षर आहे?',
        options: ['ज्ञ', 'त्र', 'श्र', 'क्ष'],
        correctAnswer: 'ज्ञ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ज्ञान" मध्ये "ज्ञ" जोडाक्षर आहे.',
      },
      {
        questionId: 'mr_t_2',
        type: 'multiple_choice',
        prompt: '"विद्यार्थी ग्रंथालयात ________ वाचतात."',
        options: ['पुस्तके', 'पाणी', 'झाडे', 'रस्ते'],
        correctAnswer: 'पुस्तके',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ग्रंथालयात पुस्तके वाचतात.',
      },
      {
        questionId: 'mr_t_3',
        type: 'multiple_choice',
        prompt: 'योग्य वाक्यरचना निवडा:',
        options: [
          'सूर्य पूर्वेला उगवतो.',
          'उगवतो पूर्वेला सूर्य.',
          'सूर्य रात्री उगवतो.',
          'पूर्वेला रात्री चंद्र उगवतो.',
        ],
        correctAnswer: 'सूर्य पूर्वेला उगवतो.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'व्याकरणदृष्ट्या योग्य वाक्य: सूर्य पूर्वेला उगवतो.',
      },
      {
        questionId: 'mr_t_4',
        type: 'reading_passage',
        passage: 'झाडे आपल्याला शुद्ध ऑक्सिजन देतात. पर्यावरण संरक्षणासाठी आपण झाडे लावली पाहिजेत.',
        prompt: 'झाडे आपल्याला काय देतात?',
        options: ['शुद्ध ऑक्सिजन (प्राणवायू)', 'धूर', 'कचरा', 'प्रदूषण'],
        correctAnswer: 'शुद्ध ऑक्सिजन (प्राणवायू)',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'झाडे आपल्याला शुद्ध प्राणवायू पुरवतात.',
      },
      {
        questionId: 'mr_t_5',
        type: 'multiple_choice',
        prompt: '"यश" या शब्दाचा विरुद्धार्थी शब्द कोणता?',
        options: ['अपयश', 'विजय', 'आनंद', 'उत्साह'],
        correctAnswer: 'अपयश',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'यशाचा विरुद्धार्थी शब्द अपयश आहे.',
      },
    ],
    adults: [
      {
        questionId: 'mr_a_1',
        type: 'multiple_choice',
        prompt: 'बसच्या पाटीवर "मुंबई" लिहिलेले योग्य रूप कोणते?',
        options: ['मुंबई', 'मुंबइ', 'मुमबई', 'मोंबई'],
        correctAnswer: 'मुंबई',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'योग्य शब्दलेखन: मुंबई.',
      },
      {
        questionId: 'mr_a_2',
        type: 'multiple_choice',
        prompt: 'रुग्णालयात तातडीच्या उपचाराचा विभाग कोणता?',
        options: ['तातडीचा उपचार विभाग (Emergency)', 'उपहारगृह', 'वाचनालय', 'तिकीट खिडकी'],
        correctAnswer: 'तातडीचा उपचार विभाग (Emergency)',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'तातडीच्या उपचारासाठी Emergency विभाग असतो.',
      },
      {
        questionId: 'mr_a_3',
        type: 'reading_passage',
        passage: 'वीज बिल भरण्याची अंतिम तारीख: २५ मार्च २०२६. विलंब शुल्क ₹५० आकारले जाईल.',
        prompt: 'बिल भरण्याची अंतिम तारीख कोणती?',
        options: ['२५ मार्च २०२६', '१ एप्रिल २०२६', '१० मे २०२६', '१५ जानेवारी २०२६'],
        correctAnswer: '२५ मार्च २०२६',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'सूचनेमध्ये अंतिम तारीख २५ मार्च २०२६ नमूद आहे.',
      },
      {
        questionId: 'mr_a_4',
        type: 'multiple_choice',
        prompt: 'बँक पावतीवर खातेदाराने स्वाक्षरी कुठे करावी?',
        options: ['ठेवीदाराची स्वाक्षरी या जागेवर', 'तारीखेवर', 'बँकेच्या शिक्क्यावर', 'व्यवस्थापकाच्या जागेवर'],
        correctAnswer: 'ठेवीदाराची स्वाक्षरी या जागेवर',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ठेवीदाराने (Depositor) स्वतःच्या स्वाक्षरीच्या जागी सही करावी.',
      },
      {
        questionId: 'mr_a_5',
        type: 'multiple_choice',
        prompt: '"औषध जेवणानंतरच घ्यावे" - याचा काय अर्थ होतो?',
        options: [
          'जेवण झाल्यावर औषध घ्यायचे आहे',
          'उपाशीपोटी घ्यायचे आहे',
          'फक्त झोपण्यापूर्वी घ्यायचे आहे',
          'कधीही घेऊ शकता',
        ],
        correctAnswer: 'जेवण झाल्यावर औषध घ्यायचे आहे',
        points: 20,
        skillCategory: 'reading',
        explanation: '"जेवणानंतर" म्हणजे जेवण केल्यानंतर औषध घेणे.',
      },
    ],
  },
};

export const getClientDiagnosticQuestions = (language = 'te', age = 20) => {
  const cohort = age < 12 ? 'kids' : age < 18 ? 'teens' : 'adults';
  const langKey = CLIENT_DIAGNOSTIC_QUESTIONS[language] ? language : 'te';
  const langData = CLIENT_DIAGNOSTIC_QUESTIONS[langKey] || CLIENT_DIAGNOSTIC_QUESTIONS.te;
  const questions = langData[cohort] || langData.adults;

  const cohortTitles = {
    kids: 'Junior Phonics & Early Reader Benchmark',
    teens: 'Youth Reading & Vocabulary Diagnostic',
    adults: 'Functional Literacy & Practical Reading Benchmark',
  };

  return {
    _id: `diag_${langKey}_${cohort}`,
    title: `${langData.nativeName} (${langData.name}) — ${cohortTitles[cohort]}`,
    code: `DIAG_${langKey.toUpperCase()}_${cohort.toUpperCase()}`,
    description: `Adaptive diagnostic assessment calibrated for ${langData.name} learners (${cohort} track, age ${age || 20}).`,
    language: langKey,
    type: 'benchmark',
    ageCohort: cohort,
    isInitialDiagnostic: true,
    targetLevel: cohort === 'kids' ? 'beginner' : 'elementary',
    timeLimitMinutes: 10,
    totalPoints: 100,
    passingScorePercentage: 60,
    questions,
  };
};
