/**
 * Diagnostic Question Bank for Age- and Language-Adaptive Initial Assessment
 * Supports: Telugu (te), Tamil (ta), Kannada (kn), Malayalam (ml), Hindi (hi), English (en), Bengali (bn), Marathi (mr)
 * Age cohorts: kids (3-11), teens (12-17), adults (18+)
 */

export const DIAGNOSTIC_QUESTIONS = {
  te: {
    name: 'Telugu',
    nativeName: 'తెలుగు',
    kids: [
      {
        questionId: 'te_k_1',
        type: 'multiple_choice',
        prompt: 'క్రింది అక్షరాలలో "అ" (అమ్మ) అక్షరాన్ని గుర్తించండి:',
        options: ['అ', 'క', 'ర', 'మ'],
        correctAnswer: 'అ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"అ" అనేది మొదటి తెలుగు అచ్చు (అమ్మ).',
      },
      {
        questionId: 'te_k_2',
        type: 'multiple_choice',
        prompt: '"క లం" కలిపితే ఏ పదం అవుతుంది?',
        options: ['కలం', 'కడవ', 'కమలం', 'కలవర'],
        correctAnswer: 'కలం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"క" మరియు "లం" కలిపితే "కలం" (Pen) అవుతుంది.',
      },
      {
        questionId: 'te_k_3',
        type: 'multiple_choice',
        prompt: 'ఆకాశంలో ఎగిరే పక్షి ఏది?',
        options: ['పావురం', 'చేప', 'పిల్లి', 'ఆవు'],
        correctAnswer: 'పావురం',
        points: 20,
        skillCategory: 'reading',
        explanation: 'పావురం గాల్లో ఎగిరే పక్షి.',
      },
      {
        questionId: 'te_k_4',
        type: 'reading_passage',
        passage: 'రాజు బడికి వెళ్ళాడు. అక్కడ స్నేహితులతో ఆడుకున్నాడు. పుస్తకం చదివాడు.',
        prompt: 'రాజు ఎక్కడికి వెళ్ళాడు?',
        options: ['బడికి', 'తోటకు', 'సినిమాకి', 'ఊరికి'],
        correctAnswer: 'బడికి',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'వాక్యంలో "రాజు బడికి వెళ్ళాడు" అని ఉంది.',
      },
      {
        questionId: 'te_k_5',
        type: 'multiple_choice',
        prompt: '"ఆవు పాలు ఇస్తుంది" - ఈ వాక్యంలో మొదటి పదం ఏది?',
        options: ['ఆవు', 'పాలు', 'ఇస్తుంది', 'పుస్తకం'],
        correctAnswer: 'ఆవు',
        points: 20,
        skillCategory: 'writing',
        explanation: 'వాక్యంలోని మొదటి పదం "ఆవు".',
      },
    ],
    teens: [
      {
        questionId: 'te_t_1',
        type: 'multiple_choice',
        prompt: '"జ్ఞానం" అనే పదంలోని సరైన ఒత్తును గుర్తించండి:',
        options: ['జ్ఞ', 'శ్వ', 'త్ర', 'క్ష'],
        correctAnswer: 'జ్ఞ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"జ్ఞానం" లో "జ్ఞ" సంయుక్తాక్షరం ఉంది.',
      },
      {
        questionId: 'te_t_2',
        type: 'multiple_choice',
        prompt: '"విద్యార్థులు గ్రంథాలయంలో ________ చదువుతున్నారు."',
        options: ['పుస్తకాలు', 'నీళ్ళు', 'చెట్లు', 'రహదారులు'],
        correctAnswer: 'పుస్తకాలు',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'గ్రంథాలయంలో పుస్తకాలు చదువుతారు.',
      },
      {
        questionId: 'te_t_3',
        type: 'multiple_choice',
        prompt: 'సరైన వాక్య నిర్మాణాన్ని ఎంచుకోండి:',
        options: [
          'సూర్యుడు తూర్పున ఉదయిస్తాడు.',
          'ఉదయిస్తాడు తూర్పున సూర్యుడు.',
          'తూర్పున సూర్యుడు పడుకుంటాడు.',
          'సూర్యుడు పశ్చిమాన ఉదయిస్తాడు.',
        ],
        correctAnswer: 'సూర్యుడు తూర్పున ఉదయిస్తాడు.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'వ్యాకరణపరంగా సరైన వాక్యం: సూర్యుడు తూర్పున ఉదయిస్తాడు.',
      },
      {
        questionId: 'te_t_4',
        type: 'reading_passage',
        passage: 'చెట్లు మనకు స్వచ్ఛమైన ప్రాణవాయువును ఇస్తాయి. పర్యావరణ పరిరక్షణకు ప్రతి ఒక్కరూ మొక్కలు నాటాలి.',
        prompt: 'చెట్లు మనకు ఏమి ఇస్తాయి?',
        options: ['స్వచ్ఛమైన ప్రాణవాయువు', 'ప్లాస్టిక్ వ్యర్థాలు', 'శబ్ద కాలుష్యం', 'పొగ'],
        correctAnswer: 'స్వచ్ఛమైన ప్రాణవాయువు',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'చెట్లు మనకు స్వచ్ఛమైన ఆక్సిజన్ (ప్రాణవాయువు) అందిస్తాయి.',
      },
      {
        questionId: 'te_t_5',
        type: 'multiple_choice',
        prompt: '"విజయం" పదానికి వ్యతిరేక పదం ఏది?',
        options: ['అపజయం', 'సంతోషం', 'గెలుపు', 'ఉత్సాహం'],
        correctAnswer: 'అపజయం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'విజయం కి వ్యతిరేక పదం అపజయం.',
      },
    ],
    adults: [
      {
        questionId: 'te_a_1',
        type: 'multiple_choice',
        prompt: 'బస్సు బోర్డుపై "హైదరాబాద్" అని రాసి ఉన్న సరైన అక్షర రూపాన్ని గుర్తించండి:',
        options: ['హైదరాబాద్', 'హైదరాబాదు', 'హైదరబాద', 'హేదరాబాద్'],
        correctAnswer: 'హైదరాబాద్',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'సరైన స్పెల్లింగ్: హైదరాబాద్.',
      },
      {
        questionId: 'te_a_2',
        type: 'multiple_choice',
        prompt: 'ఆసుపత్రిలో "వైద్యశాల / డాక్టర్ గది" సూచించే గుర్తు లేదా బోర్డు ఏది?',
        options: ['చికిత్సా విభాగం', 'సినిమా హాలు', 'బస్సు స్టాప్', 'రైల్వే టికెట్'],
        correctAnswer: 'చికిత్సా విభాగం',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ఆసుపత్రులలో వైద్య సేవలు అందించేది చికిత్సా విభాగం.',
      },
      {
        questionId: 'te_a_3',
        type: 'reading_passage',
        passage: 'విద్యుత్ బిల్లు చెల్లింపు చివరి తేదీ: 25 మార్చి 2026. ఆలస్య రుసుము రూ. 50 వర్తిస్తుంది.',
        prompt: 'బిల్లు గడువు తేదీ ఎప్పుడు?',
        options: ['25 మార్చి 2026', '1 జనవరి 2026', '10 ఏప్రిల్ 2026', '30 మే 2026'],
        correctAnswer: '25 మార్చి 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'నోటీసులో స్పష్టంగా చివరి తేదీ 25 మార్చి 2026 అని ఉంది.',
      },
      {
        questionId: 'te_a_4',
        type: 'multiple_choice',
        prompt: 'బ్యాంకులో డబ్బు జమ చేసే ఫారమ్‌లో మీ సంతకం ఎక్కడ చేయాలి?',
        options: ['ఖాతాదారుని సంతకం వద్ద', 'తేదీ వద్ద', 'బ్యాంకు సీల్ పైన', 'బ్యాంకు మేనేజర్ స్థానంలో'],
        correctAnswer: 'ఖాతాదారుని సంతకం వద్ద',
        points: 20,
        skillCategory: 'writing',
        explanation: 'డిపాజిటర్ సంతకం నిర్దేశించిన స్థానంలో చేయాలి.',
      },
      {
        questionId: 'te_a_5',
        type: 'multiple_choice',
        prompt: '"మందులు ఆహారం తర్వాత మాత్రమే వేసుకోవాలి" - దీని అర్థం ఏమిటి?',
        options: [
          'భోజనం చేసిన తర్వాత మందు వేసుకోవాలి',
          'ఖాళీ కడుపుతో మాత్రమే వేసుకోవాలి',
          'రాత్రి నిద్రపోయే ముందు మాత్రమే వేసుకోవాలి',
          'ఎప్పుడైనా వేసుకోవచ్చు',
        ],
        correctAnswer: 'భోజనం చేసిన తర్వాత మందు వేసుకోవాలి',
        points: 20,
        skillCategory: 'reading',
        explanation: '"ఆహారం తర్వాత" అంటే భోజనం లేదా అల్పాహారం తిన్న తరువాత.',
      },
    ],
  },

  ta: {
    name: 'Tamil',
    nativeName: 'தமிழ்',
    kids: [
      {
        questionId: 'ta_k_1',
        type: 'multiple_choice',
        prompt: 'கீழ்கண்டவற்றில் முதல் தமிழ் உயிர் எழுத்து "அ" எது?',
        options: ['அ', 'க', 'ப', 'ம'],
        correctAnswer: 'அ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"அ" என்பது முதல் தமிழ் உயிர் எழுத்து (அம்மா).',
      },
      {
        questionId: 'ta_k_2',
        type: 'multiple_choice',
        prompt: '"ப ல்" சேர்த்தால் என்ன சொல் உருவாகும்?',
        options: ['பல்', 'படம்', 'பட்டம்', 'பந்து'],
        correctAnswer: 'பல்',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"ப" + "ல்" = "பல்" (Tooth).',
      },
      {
        questionId: 'ta_k_3',
        type: 'multiple_choice',
        prompt: 'மரங்களில் பழங்கள் தரும் தாவரம் எது?',
        options: ['மரம்', 'கல்', 'குளம்', 'வானம்'],
        correctAnswer: 'மரம்',
        points: 20,
        skillCategory: 'reading',
        explanation: 'மரம் நமக்கு பழங்களை வழங்குகிறது.',
      },
      {
        questionId: 'ta_k_4',
        type: 'reading_passage',
        passage: 'அன்பு பள்ளிக்குச் சென்றான். அவன் புதிய புத்தகம் படித்தான்.',
        prompt: 'அன்பு எதைப் படித்தான்?',
        options: ['புத்தகம்', 'செய்தி', 'விளம்பரம்', 'படம்'],
        correctAnswer: 'புத்தகம்',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'வாக்கியத்தில் "அவன் புதிய புத்தகம் படித்தான்" என்றுள்ளது.',
      },
      {
        questionId: 'ta_k_5',
        type: 'multiple_choice',
        prompt: '"அம்மா உணவு சமைத்தார்" - இதில் முதல் சொல் எது?',
        options: ['அம்மா', 'உணவு', 'சமைத்தார்', 'பள்ளி'],
        correctAnswer: 'அம்மா',
        points: 20,
        skillCategory: 'writing',
        explanation: 'வாக்கியத்தின் முதல் சொல் "அம்மா".',
      },
    ],
    teens: [
      {
        questionId: 'ta_t_1',
        type: 'multiple_choice',
        prompt: '"கல்வி" என்ற சொல்லில் உள்ள மெய்யெழுத்து எது?',
        options: ['ல்', 'க', 'வி', 'அ'],
        correctAnswer: 'ல்',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ல்" என்பது புள்ளி வைத்த மெய்யெழுத்து.',
      },
      {
        questionId: 'ta_t_2',
        type: 'multiple_choice',
        prompt: '"மாணவர்கள் நூலகத்தில் ________ படிக்கிறார்கள்."',
        options: ['நூல்கள்', 'தண்ணீர்', 'மரங்கள்', 'சாலையை'],
        correctAnswer: 'நூல்கள்',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'நூலகத்தில் நூல்கள் (புத்தகங்கள்) படிப்பார்கள்.',
      },
      {
        questionId: 'ta_t_3',
        type: 'multiple_choice',
        prompt: 'சரியான வாக்கிய அமைப்பைத் தேர்ந்தெடுக்கவும்:',
        options: [
          'சூரியன் கிழக்கில் உதிக்கிறது.',
          'உதிக்கிறது கிழக்கில் சூரியன்.',
          'சூரியன் இரவில் உதிக்கிறது.',
          'கிழக்கில் சந்திரன் உதிக்கிறது.',
        ],
        correctAnswer: 'சூரியன் கிழக்கில் உதிக்கிறது.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'இலக்கணப்படி சரியான வாக்கியம்: சூரியன் கிழக்கில் உதிக்கிறது.',
      },
      {
        questionId: 'ta_t_4',
        type: 'reading_passage',
        passage: 'மழைநீர் சேகரிப்பு நிலத்தடி நீர்மட்டத்தை உயர்த்தும் மிக முக்கியமான வழிமுறையாகும்.',
        prompt: 'மழைநீர் சேகரிப்பு எதை உயர்த்தும்?',
        options: ['நிலத்தடி நீர்மட்டம்', 'வெப்பநிலை', 'மாசுபாடு', 'காற்றழுத்தம்'],
        correctAnswer: 'நிலத்தடி நீர்மட்டம்',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'மழைநீர் சேகரிப்பு நிலத்தடி நீர்மட்டத்தை உயர்த்துகிறது.',
      },
      {
        questionId: 'ta_t_5',
        type: 'multiple_choice',
        prompt: '"நன்மை" என்பதன் எதிர்ச்சொல் எது?',
        options: ['தீமை', 'அன்பு', 'உண்மை', 'அமைதி'],
        correctAnswer: 'தீமை',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'நன்மை என்பதன் எதிர்ச்சொல் தீமை.',
      },
    ],
    adults: [
      {
        questionId: 'ta_a_1',
        type: 'multiple_choice',
        prompt: 'பேருந்து பலகையில் "சென்னை" என்ற சரியான எழுத்தைக் கண்டறியவும்:',
        options: ['சென்னை', 'சென்னைய்', 'செனை', 'செண்ணை'],
        correctAnswer: 'சென்னை',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'சரியான எழுத்துக்கூட்டல்: சென்னை.',
      },
      {
        questionId: 'ta_a_2',
        type: 'multiple_choice',
        prompt: 'மருத்துவமனையில் அவசர சிகிச்சை பிரிவை குறிக்கும் சொல் எது?',
        options: ['அவசர சிகிச்சை பிரிவு', 'உணவகம்', 'நூலகம்', 'பூங்கா'],
        correctAnswer: 'அவசர சிகிச்சை பிரிவு',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'அவசர மருத்துவ சேவை தரும் இடம் அவசர சிகிச்சை பிரிவு (Emergency).',
      },
      {
        questionId: 'ta_a_3',
        type: 'reading_passage',
        passage: 'மின்சாரக் கட்டணம் செலுத்த கடைசி நாள்: 20 ஏப்ரல் 2026. தாமதக் கட்டணம் ரூ. 40.',
        prompt: 'கட்டணம் செலுத்த கடைசி நாள் எது?',
        options: ['20 ஏப்ரல் 2026', '1 மே 2026', '15 மார்ச் 2026', '10 ஜூன் 2026'],
        correctAnswer: '20 ஏப்ரல் 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'அறிவிப்பில் கடைசி நாள் 20 ஏப்ரல் 2026 என்று குறிப்பிடப்பட்டுள்ளது.',
      },
      {
        questionId: 'ta_a_4',
        type: 'multiple_choice',
        prompt: 'வங்கி படிவத்தில் பணத்தை செலுத்துபவர் கையொப்பம் எங்கு இட வேண்டும்?',
        options: ['வாடிக்கையாளர் கையொப்பம் இடத்தில்', 'தேதி இடத்தில்', 'மேலாளர் கையொப்பத்தில்', 'தொகை இடத்தில்'],
        correctAnswer: 'வாடிக்கையாளர் கையொப்பம் இடத்தில்',
        points: 20,
        skillCategory: 'writing',
        explanation: 'வாடிக்கையாளர் கையொப்பம் (Customer Signature) பகுதியில் கையொப்பமிட வேண்டும்.',
      },
      {
        questionId: 'ta_a_5',
        type: 'multiple_choice',
        prompt: '"மருந்தை உணவுக்குப் பின் உட்கொள்ளவும்" - இதன் பொருள் என்ன?',
        options: [
          'சாப்பிட்ட பிறகு மருந்து சாப்பிட வேண்டும்',
          'வெறும் வயிற்றில் சாப்பிட வேண்டும்',
          'தூங்குவதற்கு முன் மட்டும் சாப்பிட வேண்டும்',
          'எப்போது வேண்டுமானாலும் சாப்பிடலாம்',
        ],
        correctAnswer: 'சாப்பிட்ட பிறகு மருந்து சாப்பிட வேண்டும்',
        points: 20,
        skillCategory: 'reading',
        explanation: '"உணவுக்குப் பின்" என்பது உணவு உண்ட பிறகு உட்கொள்வதைக் குறிக்கிறது.',
      },
    ],
  },

  kn: {
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    kids: [
      {
        questionId: 'kn_k_1',
        type: 'multiple_choice',
        prompt: 'ಮೊದಲ ಕನ್ನಡ ಸ್ವರ "ಅ" (ಅಮ್ಮ) ಅಕ್ಷರವನ್ನು ಗುರುತಿಸಿ:',
        options: ['ಅ', 'ಕ', 'ರ', 'ಮ'],
        correctAnswer: 'ಅ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ಅ" ಮೊದಲ ಕನ್ನಡ ಸ್ವರಾಕ್ಷರವಾಗಿದೆ.',
      },
      {
        questionId: 'kn_k_2',
        type: 'multiple_choice',
        prompt: '"ಮ ರ" ಸೇರಿಸಿದರೆ ಯಾವ ಪದವಾಗುತ್ತದೆ?',
        options: ['ಮರ', 'ಮನೆ', 'ಮಗು', 'ಮಣ್ಣು'],
        correctAnswer: 'ಮರ',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: '"ಮ" ಮತ್ತು "ರ" ಸೇರಿ "ಮರ" (Tree) ಆಗುತ್ತದೆ.',
      },
      {
        questionId: 'kn_k_3',
        type: 'multiple_choice',
        prompt: 'ನಮಗೆ ಹಾಲು ಕೊಡುವ ಪ್ರಾಣಿ ಯಾವುದು?',
        options: ['ಹಸು', 'ಹುಲಿ', 'ಸಿಂಹ', 'ಗಿಳಿ'],
        correctAnswer: 'ಹಸು',
        points: 20,
        skillCategory: 'reading',
        explanation: 'ಹಸು ನಮಗೆ ಸಿಹಿಯಾದ ಹಾಲನ್ನು ನೀಡುತ್ತದೆ.',
      },
      {
        questionId: 'kn_k_4',
        type: 'reading_passage',
        passage: 'ರಾಜು ಶಾಲೆಗೆ ಹೋದನು. ಅಲ್ಲಿ ಗೆಳೆಯರೊಂದಿಗೆ ಆಟವಾಡಿದನು ಮತ್ತು ಪುಸ್ತಕ ಓದಿದನು.',
        prompt: 'ರಾಜು ಎಲ್ಲಿಗೆ ಹೋದನು?',
        options: ['ಶಾಲೆಗೆ', 'ಮಾರುಕಟ್ಟೆಗೆ', 'ತೋಟಕ್ಕೆ', 'ಊರಿಗೆ'],
        correctAnswer: 'ಶಾಲೆಗೆ',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ವಾಕ್ಯದಲ್ಲಿ "ರಾಜು ಶಾಲೆಗೆ ಹೋದನು" ಎಂದು ಬರೆಯಲಾಗಿದೆ.',
      },
      {
        questionId: 'kn_k_5',
        type: 'multiple_choice',
        prompt: '"ಹಸು ಹುಲ್ಲು ತಿನ್ನುತ್ತದೆ" - ಈ ವಾಕ್ಯದ ಮೊದಲ ಪದ ಯಾವುದು?',
        options: ['ಹಸು', 'ಹುಲ್ಲು', 'ತಿನ್ನುತ್ತದೆ', 'ಹಾಲು'],
        correctAnswer: 'ಹಸು',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ವಾಕ್ಯದ ಮೊದಲ ಪದ "ಹಸು".',
      },
    ],
    teens: [
      {
        questionId: 'kn_t_1',
        type: 'multiple_choice',
        prompt: '"ಜ್ಞಾನ" ಪದದಲ್ಲಿರುವ ಸಂಯುಕ್ತಾಕ್ಷರ ಯಾವುದು?',
        options: ['ಜ್ಞ', 'ತ್ರ', 'ಶ್ರ', 'ಕ್ಷ'],
        correctAnswer: 'ಜ್ಞ',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"ಜ್ಞಾನ" ಪದದಲ್ಲಿ "ಜ್ಞ" ಒತ್ತು ಅಕ್ಷರವಿದೆ.',
      },
      {
        questionId: 'kn_t_2',
        type: 'multiple_choice',
        prompt: '"ವಿದ್ಯಾರ್ಥಿಗಳು ಗ್ರಂಥಾಲಯದಲ್ಲಿ ________ ಓದುತ್ತಾರೆ."',
        options: ['ಪುಸ್ತಕಗಳನ್ನು', 'ನೀರನ್ನು', 'ಗಿಡಗಳನ್ನು', 'ರಸ್ತೆಯನ್ನು'],
        correctAnswer: 'ಪುಸ್ತಕಗಳನ್ನು',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ಗ್ರಂಥಾಲಯದಲ್ಲಿ ಪುಸ್ತಕಗಳನ್ನು ಓದುತ್ತಾರೆ.',
      },
      {
        questionId: 'kn_t_3',
        type: 'multiple_choice',
        prompt: 'ಸರಿಯಾದ ವಾಕ್ಯ ರಚನೆಯನ್ನು ಆರಿಸಿ:',
        options: [
          'ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
          'ಹುಟ್ಟುತ್ತಾನೆ ಪೂರ್ವದಲ್ಲಿ ಸೂರ್ಯನು.',
          'ಸೂರ್ಯನು ಪಶ್ಚಿಮದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
          'ಪೂರ್ವದಲ್ಲಿ ರಾತ್ರಿ ಆಗುತ್ತದೆ.',
        ],
        correctAnswer: 'ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ವ್ಯಾಕರಣಬದ್ಧ ಸರಿಯಾದ ವಾಕ್ಯ: ಸೂರ್ಯನು ಪೂರ್ವದಲ್ಲಿ ಹುಟ್ಟುತ್ತಾನೆ.',
      },
      {
        questionId: 'kn_t_4',
        type: 'reading_passage',
        passage: 'ಮರಗಳು ನಮಗೆ ಶುದ್ಧ ಗಾಳಿಯನ್ನು ನೀಡುತ್ತವೆ. ಪರಿಸರ ರಕ್ಷಣೆಗಾಗಿ ನಾವು ಗಿಡಗಳನ್ನು ಬೆಳೆಸಬೇಕು.',
        prompt: 'ಮರಗಳು ನಮಗೆ ಏನನ್ನು ನೀಡುತ್ತವೆ?',
        options: ['ಶುದ್ಧ ಗಾಳಿ (ಆಮ್ಲಜನಕ)', 'ಧೂಳು', 'ಶಬ್ದ ಮಾಲಿನ್ಯ', 'ಕಸ'],
        correctAnswer: 'ಶುದ್ಧ ಗಾಳಿ (ಆಮ್ಲಜನಕ)',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ಮರಗಳು ನಮಗೆ ಶುದ್ಧ ಗಾಳಿಯನ್ನು ಒದಗಿಸುತ್ತವೆ.',
      },
      {
        questionId: 'kn_t_5',
        type: 'multiple_choice',
        prompt: '"ಗೆಲುವು" ಪದದ ವಿರುದ್ಧ ಪದ ಯಾವುದು?',
        options: ['ಸೋಲು', 'ಖುಷಿ', 'ಉತ್ಸಾಹ', 'ಸಂತೋಷ'],
        correctAnswer: 'ಸೋಲು',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ಗೆಲುವು ಪದದ ವಿರುದ್ಧ ಪದ ಸೋಲು.',
      },
    ],
    adults: [
      {
        questionId: 'kn_a_1',
        type: 'multiple_choice',
        prompt: 'ಬಸ್ ಬೋರ್ಡ್‌ನಲ್ಲಿ "ಬೆಂಗಳೂರು" ಎಂದು ಬರೆದಿರುವ ಸರಿಯಾದ ರೂಪ ಯಾವುದು?',
        options: ['ಬೆಂಗಳೂರು', 'ಬೆಂಗಳೂರುರ', 'ಬೆಂಗಲೂರು', 'ಬೆಂಗಾಳೂರು'],
        correctAnswer: 'ಬೆಂಗಳೂರು',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'ಸರಿಯಾದ ಕಾಗುಣಿತ: ಬೆಂಗಳೂರು.',
      },
      {
        questionId: 'kn_a_2',
        type: 'multiple_choice',
        prompt: 'ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತುರ್ತು ಚಿಕಿತ್ಸೆ ನೀಡುವ ವಿಭಾಗ ಯಾವುದು?',
        options: ['ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ', 'ಉಪಹಾರ ಗೃಹ', 'ವಾಚನಾಲಯ', 'ಬಸ್ ನಿಲ್ದಾಣ'],
        correctAnswer: 'ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'ತುರ್ತು ಸೇವೆ ನೀಡುವ ಸ್ಥಳ ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗ (Emergency).',
      },
      {
        questionId: 'kn_a_3',
        type: 'reading_passage',
        passage: 'ವಿದ್ಯುತ್ ಬಿಲ್ ಪಾವತಿಸಲು ಕೊನೆಯ ದಿನಾಂಕ: 22 ಮಾರ್ಚ್ 2026. ವಿಳಂಬ ಶುಲ್ಕ ರೂ. 45.',
        prompt: 'ಬಿಲ್ ಪಾವತಿಸಲು ಕೊನೆಯ ದಿನಾಂಕ ಯಾವುದು?',
        options: ['22 ಮಾರ್ಚ್ 2026', '1 ಏಪ್ರಿಲ್ 2026', '10 ಮೇ 2026', '5 ಜನವರಿ 2026'],
        correctAnswer: '22 ಮಾರ್ಚ್ 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'ಸೂಚನೆಯಲ್ಲಿ ಕೊನೆಯ ದಿನಾಂಕ 22 ಮಾರ್ಚ್ 2026 ಎಂದು ನಮೂದಿಸಲಾಗಿದೆ.',
      },
      {
        questionId: 'kn_a_4',
        type: 'multiple_choice',
        prompt: 'ಬ್ಯಾಂಕ್ ಚಲನ್‌ನಲ್ಲಿ ಠೇವಣಿದಾರರ ಸಹಿಯನ್ನು ಎಲ್ಲಿ ಮಾಡಬೇಕು?',
        options: ['ಖಾತೆದಾರರ / ಠೇವಣಿದಾರರ ಸಹಿ ಜಾಗದಲ್ಲಿ', 'ದಿನಾಂಕದ ಮೇಲೆ', 'ಮೊತ್ತದ ಮೇಲೆ', 'ಮ್ಯಾನೇಜರ್ ಸ್ಥಾನದಲ್ಲಿ'],
        correctAnswer: 'ಖಾತೆದಾರರ / ಠೇವಣಿದಾರರ ಸಹಿ ಜಾಗದಲ್ಲಿ',
        points: 20,
        skillCategory: 'writing',
        explanation: 'ಗ್ರಾಹಕರ ಸಹಿ (Depositor Signature) ಇರುವ ಸ್ಥಳದಲ್ಲಿ ಸಹಿ ಮಾಡಬೇಕು.',
      },
      {
        questionId: 'kn_a_5',
        type: 'multiple_choice',
        prompt: '"ಔಷಧಿಯನ್ನು ಊಟದ ನಂತರ ಸೇವಿಸಿ" - ಇದರ ಅರ್ಥವೇನು?',
        options: [
          'ಊಟ ಮಾಡಿದ ನಂತರ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಮಲಗುವ ಮುನ್ನ ಮಾತ್ರ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
          'ಯಾವಾಗಲಾದರೂ ತೆಗೆದುಕೊಳ್ಳಬಹುದು',
        ],
        correctAnswer: 'ಊಟ ಮಾಡಿದ ನಂತರ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳಬೇಕು',
        points: 20,
        skillCategory: 'reading',
        explanation: '"ಊಟದ ನಂತರ" ಎಂದರೆ ಊಟ ಮಾಡಿದ ಬಳಿಕ ಔಷಧ ಸೇವಿಸುವುದು.',
      },
    ],
  },

  en: {
    name: 'English',
    nativeName: 'English',
    kids: [
      {
        questionId: 'en_k_1',
        type: 'multiple_choice',
        prompt: 'Which letter does "Apple" start with?',
        options: ['A', 'B', 'C', 'D'],
        correctAnswer: 'A',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'Apple starts with the letter A.',
      },
      {
        questionId: 'en_k_2',
        type: 'multiple_choice',
        prompt: 'Combine letters "C - A - T" to form a word:',
        options: ['Cat', 'Car', 'Cup', 'Cap'],
        correctAnswer: 'Cat',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'C + A + T spells Cat.',
      },
      {
        questionId: 'en_k_3',
        type: 'multiple_choice',
        prompt: 'Which animal says "Meow"?',
        options: ['Cat', 'Dog', 'Cow', 'Duck'],
        correctAnswer: 'Cat',
        points: 20,
        skillCategory: 'reading',
        explanation: 'A cat makes the meow sound.',
      },
      {
        questionId: 'en_k_4',
        type: 'reading_passage',
        passage: 'Sam went to the park. He played on the red slide and ate an ice cream.',
        prompt: 'What color was the slide?',
        options: ['Red', 'Blue', 'Green', 'Yellow'],
        correctAnswer: 'Red',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'The story states Sam played on the "red slide".',
      },
      {
        questionId: 'en_k_5',
        type: 'multiple_choice',
        prompt: 'Which word rhymes with "Sun"?',
        options: ['Run', 'Cat', 'Dog', 'Car'],
        correctAnswer: 'Run',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'Sun and Run end in the same sound (-un).',
      },
    ],
    teens: [
      {
        questionId: 'en_t_1',
        type: 'multiple_choice',
        prompt: 'Choose the correct spelling:',
        options: ['Knowledge', 'Knowlege', 'Nowledge', 'Knolwedge'],
        correctAnswer: 'Knowledge',
        points: 20,
        skillCategory: 'phonics',
        explanation: 'The correct spelling is Knowledge.',
      },
      {
        questionId: 'en_t_2',
        type: 'multiple_choice',
        prompt: 'Complete the sentence: "Students borrow books from the _______."',
        options: ['Library', 'Stadium', 'Hospital', 'Bakery'],
        correctAnswer: 'Library',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'A library is where books are borrowed.',
      },
      {
        questionId: 'en_t_3',
        type: 'multiple_choice',
        prompt: 'Choose the grammatically correct sentence:',
        options: [
          'The sun rises in the east.',
          'The sun rise in the east.',
          'Rises the sun in the east.',
          'The sun in the east rising.',
        ],
        correctAnswer: 'The sun rises in the east.',
        points: 20,
        skillCategory: 'writing',
        explanation: 'Subject-verb agreement: "The sun rises in the east."',
      },
      {
        questionId: 'en_t_4',
        type: 'reading_passage',
        passage: 'Trees absorb carbon dioxide and release fresh oxygen, playing a vital role in balancing our ecosystem.',
        prompt: 'What do trees release?',
        options: ['Fresh oxygen', 'Carbon dioxide', 'Smoke', 'Dust'],
        correctAnswer: 'Fresh oxygen',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'Trees release fresh oxygen during photosynthesis.',
      },
      {
        questionId: 'en_t_5',
        type: 'multiple_choice',
        prompt: 'What is the antonym (opposite) of "Success"?',
        options: ['Failure', 'Victory', 'Happiness', 'Growth'],
        correctAnswer: 'Failure',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'The opposite of success is failure.',
      },
    ],
    adults: [
      {
        questionId: 'en_a_1',
        type: 'multiple_choice',
        prompt: 'Which sign indicates where to exit a public building safely?',
        options: ['EMERGENCY EXIT', 'NO ENTRY', 'PARKING ONLY', 'STAFF ONLY'],
        correctAnswer: 'EMERGENCY EXIT',
        points: 20,
        skillCategory: 'phonics',
        explanation: '"EMERGENCY EXIT" marks the safe way out.',
      },
      {
        questionId: 'en_a_2',
        type: 'multiple_choice',
        prompt: 'Where would you find a physician or doctor in a healthcare center?',
        options: ['Outpatient Consultation Room', 'Ticket Counter', 'Luggage Cloakroom', 'Cafeteria'],
        correctAnswer: 'Outpatient Consultation Room',
        points: 20,
        skillCategory: 'vocabulary',
        explanation: 'Consultation rooms are where doctors examine patients.',
      },
      {
        questionId: 'en_a_3',
        type: 'reading_passage',
        passage: 'Utility Bill Notice: Total Amount Due is $45.00. Payment must be completed before April 15, 2026 to avoid a $5.00 late fee.',
        prompt: 'When is the bill payment deadline?',
        options: ['April 15, 2026', 'May 1, 2026', 'March 1, 2026', 'December 31, 2026'],
        correctAnswer: 'April 15, 2026',
        points: 20,
        skillCategory: 'comprehension',
        explanation: 'The notice specifies payment before April 15, 2026.',
      },
      {
        questionId: 'en_a_4',
        type: 'multiple_choice',
        prompt: 'On a bank deposit slip, where should the account holder place their signature?',
        options: ['Depositor Signature line', 'Date column', 'Bank stamp box', 'Total amount line'],
        correctAnswer: 'Depositor Signature line',
        points: 20,
        skillCategory: 'writing',
        explanation: 'Signatures are placed on the designated signature line.',
      },
      {
        questionId: 'en_a_5',
        type: 'multiple_choice',
        prompt: 'Medicine Instruction: "Take 1 tablet twice daily after meals." What does this mean?',
        options: [
          'Take 1 tablet in the morning and 1 at night after eating',
          'Take 2 tablets before breakfast on an empty stomach',
          'Take all tablets at once before sleeping',
          'Take only when headache occurs',
        ],
        correctAnswer: 'Take 1 tablet in the morning and 1 at night after eating',
        points: 20,
        skillCategory: 'reading',
        explanation: '"Twice daily after meals" indicates two doses taken after food.',
      },
    ],
  },
};

// Fallback generator for languages where specific bank isn't customized yet
export const getDiagnosticAssessmentData = (language = 'te', age = 20) => {
  const cohort = age < 12 ? 'kids' : age < 18 ? 'teens' : 'adults';
  const langKey = DIAGNOSTIC_QUESTIONS[language] ? language : 'te';
  const langData = DIAGNOSTIC_QUESTIONS[langKey] || DIAGNOSTIC_QUESTIONS.te;
  const questions = langData[cohort] || langData.adults;

  const cohortTitles = {
    kids: 'Junior Phonics & Early Reader Benchmark',
    teens: 'Youth Reading & Vocabulary Diagnostic',
    adults: 'Functional Literacy & Practical Reading Benchmark',
  };

  return {
    _id: `diag_${langKey}_${cohort}`,
    title: `${langData.nativeName} (${langData.name}) — ${cohortTitles[cohort]}`,
    code: `DIAG_${langKey.toUpperCase()}_${cohort.toUpperCase()}`,
    description: `Adaptive diagnostic assessment calibrated for ${langData.name} learners (${cohort} track, age ${age || 20}).`,
    language: langKey,
    type: 'benchmark',
    ageCohort: cohort,
    isInitialDiagnostic: true,
    targetLevel: cohort === 'kids' ? 'beginner' : 'elementary',
    timeLimitMinutes: 10,
    totalPoints: 100,
    passingScorePercentage: 60,
    questions,
  };
};
